### PR TITLE
Perform a shallow clone for the beats repo

### PR DESCRIPTION
**Pull request by alexsapran**
## What does this PR do?

When cloning the beats repo inside the BK agent, we perform a full clone, adding depth=1 only fetches the latest commit, speeding up the clone operation.

## Why is it important?

This is a follow-up review of #3924

### CODE REVIEW

**Comment by amitkanfer** [comment]
@alexsapran amazing!
easy speed-up. i wonder if there are other pipelines that can benefit from the same improvement?

**Review by cmacknz — APPROVED** [review]

**Comment by fearful-symmetry** [comment]
@alexsapran have you tested this against the serverless beats tests? You can temporarily remove the `if: "build.env('CRON') == 'yes'"` from `pipeline.yml` to add the test to CI.

**Comment by alexsapran** [comment]
> @alexsapran have you tested this against the serverless beats tests? You can temporarily remove the `if: "build.env('CRON') == 'yes'"` from `pipeline.yml` to add the test to CI.

No, I had not, but I would surprised if this would break the pipeline. 
I triggered the BK job manually using the `custom rebuild` option of BK and set the env `CRON=yes` so there is no need to alter the pipeline definition. 
The [build is running](https://buildkite.com/elastic/elastic-agent/builds/5698#018c86df-157b-4cf8-bb91-19fda5a3727e) and seems to execute the checkout fine.

**Comment by alexsapran** [comment]
The build is failing on another unrelated step for windows. The [serverless beats step](https://buildkite.com/elastic/elastic-agent/builds/5698#_) passed
Screenshot 2023-12-20 at 1 52 03 PM

I will re-trigger another build

**Review by pchila — APPROVED** [review]

**Review by michalpristas — APPROVED** [review]

**Pull request merged**
