### PR TITLE
Update go.mod to Go 1.18, update notice.

### PR DESCRIPTION
**Pull request by cmacknz**
We forgot to update the Go version in the go.mod file to Go 1.18. This PR does that, and updates the notice file.

### CODE REVIEW

**Review by aleksmaus — APPROVED** [review]
Thank you!

**Comment by cmacknz** [comment]
The Mac build seems to be failing with what looks like a provisioning error:

```
2022-09-08T14:31:30.999Z] [Google Cloud Storage Plugin] Found 1 files to download from pattern: gs://fleet-ci-temp/elastic-agent/elastic-agent-mbp/PR-1120-3/source/source.tgz
[2022-09-08T14:32:09.157Z] ERROR: Issue with creating launcher for agent monterey_cd19ac98019c4. The agent has not been fully initialized yet
[2022-09-08T14:32:09.158Z] ERROR: Issue with creating launcher for agent monterey_cd19ac98019c4. The agent has not been fully initialized yet
```

@v1v have you seen this before? Is there something we can do to fix it? Should we skip Mac builds on PRs?

**Comment by v1v** [comment]
There are errors with the workers and the controller.
```
15:41:59  java.io.EOFException
15:41:59  	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2832)
15:41:59  	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3307)
15:41:59  	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:934)
15:41:59  	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:396)
15:41:59  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
15:41:59  	at hudson.remoting.Command.readFrom(Command.java:142)
15:41:59  	at hudson.remoting.Command.readFrom(Command.java:128)
15:41:59  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
15:41:59  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
15:41:59  Caused: java.io.IOException: Unexpected termination of the channel
```

@elastic/ci-systems , as you own the CI controller (`fleet-ci`), do you happen to know whether there is any known issue with the connectivity or something relevant?

**Comment by cmacknz** [comment]
Merged as the failure here is unrelated to the change. Would be great to figure out if there's something we can do to prevent this type of build failure in the future.

**Pull request merged**
