### PR TITLE
Fix wrong binary for setting capabilities

### PR DESCRIPTION
**Pull request by rdner**
## What does this PR do?

Since we transitioned to `agentbeat` we now need to use `setcap` on a different binary.

## Why is it important?

The capabilities were not set correctly before this change.

## Checklist

- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)

## How to test this PR locally

```sh
PLATFORMS=linux/amd64 PACKAGES=docker mage package
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Review by emilioalvap — APPROVED** [review]
LGTM

**Comment by rdner** [comment]
We have a problem, fixing this caused our Docker images to grow in size by 277MB. Technically `setcap` is editing the binary, hence the new Docker layer:

Before `docker history` showed:

```
<missing>      4 minutes ago   RUN /bin/sh -c setcap cap_net_raw,cap_setuid…   0B        buildkit.dockerfile.v0
```

Now:

```
<missing>      6 minutes ago   RUN /bin/sh -c setcap cap_net_raw,cap_setuid…   277MB     buildkit.dockerfile.v0
```

**Comment by amitkanfer** [comment]
Not good... any path to avoid this?

**Comment by rdner** [comment]
@amitkanfer looks like I sorted this out, see https://github.com/elastic/elastic-agent/pull/5073

**Pull request merged**
