### PR TITLE
Increase sleep time for install progress tests

### LINKED ISSUE #3489: Flaky test: TestProgress/single_step_delayed_failure
## Flaky Test

* **Test Name:** TestProgress/single_step_delayed_failure
* **Link:** https://github.com/elastic/elastic-agent/blob/123ba9ce80c9865f72fa3659b5cafe9b51954f49/internal/pkg/agent/install/progress_test.go#L45-L60
* **Branch:** https://fleet-ci.elastic.co/job/elastic-agent/job/elastic-agent-mbp/job/PR-3482/
* **Artifact Link:** https://fleet-ci.elastic.co/job/elastic-agent/job/elastic-agent-mbp/job/PR-3482/7/artifact/
* **Notes:** It seems the regexp matching is flaky (mostly on windows). The number of dots in the log seems to be off by 1

### Stack Trace

```
=== RUN   TestProgress/single_step_delayed_failure
    progress_test.go:59: 
        	Error Trace:	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3482/src/github.com/elastic/elastic-agent/internal/pkg/agent/install/progress_test.go:59
        	Error:      	Expect "step 1 starting... FAILED
        	            	" to match "step 1 starting\.{3}\.+ FAILED\n"
        	Test:       	TestProgress/single_step_delayed_failure
--- FAIL: TestProgress/single_step_delayed_failure (0.02s)
```

### PR DESCRIPTION
**Pull request by pchila**
Increase the sleep timeout for testcase `TestProgress/single_step_delayed_failure` to avoid flakiness on Windows.
The tick interval for the test is set to 10 ms but the code allows for variance between 65% and 250% of such value and it expects at least 1 tick to happen (it is asserted on the regexp match as at least 1 additional `.`)

Original sleep time of 15 ms would not cover the whole possible interval, after testing on windows with different timings the most reliable seems to be ~100ms (40-50 ms would still yield a few failures when run 10000 times in a loop)

## What does this PR do?
Remove flakiness for test `TestProgress/single_step_delayed_failure`

## Why is it important?
To avoid random failures in CI build

## Checklist

- [ ] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Author's Checklist

- [ ]

## Related issues

- Closes #3489

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by pchila** [comment]
buildkite test this

**Review by blakerouse — APPROVED** [review]
Looks good.

**Comment by pchila** [comment]
buildkite test this

**Comment by pchila** [comment]
buildkite test this

**Review by belimawr — APPROVED** [review]

**Comment by pchila** [comment]
buildkite test this

**Pull request merged**
