### PR TITLE
github-actions: remove apm-ci role/secret vault

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Use GitHub secrets for the slack bot and the `github.secret` with the proper permissions

## Why is it important?

Remove the support for accessing vault to gather those secrets.
This project uses Buildktie therefore it can use the github-bot user.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by v1v** [comment]
@pierrehilbert, do you think we can merge this PR? CI failures didn't test these changes, this is about the GitHub action, I think we are safe to merge it as is.

Thanks

**Comment by pierrehilbert** [comment]
Yes failures are unrelated. I'm forcing the merge.

**Comment by rdner** [comment]
@v1v @pierrehilbert This PR also removes the `Setup Git` step, which broke the automation https://github.com/elastic/elastic-agent/actions/runs/9393037152/job/25868378197

**Comment by rdner** [comment]
Although it's broken, this PR has to be backported to 8.14 and the following fix too.

**Comment by v1v** [comment]
> Although it's broken, this PR has to be backported to 8.14 and the following fix too.

Why?
As far as I see it only uses `main`

**Comment by rdner** [comment]
@v1v the idea is that we would trigger this action manually on a release branch that requires it. Sometimes snapshots expire and we cannot backport anything to the release branch unless we run this action.

**Pull request merged**
