### PR TITLE
Disable signature validation for policy and actions

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

This disables the policy and the agent validation for 8.8.0 release as requested in the 
https://github.com/elastic/security-team/issues/6501

The policy and the action signature validation is handled by Endpoint only in order to reduce the impact and the scope of the release of the new feature.

## Why is it important?

The change is requested for 8.8.0 in order to reduce the impact of the completely new feature.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## How to test this PR locally

Full regression testing. The agent can install/enroll, receive policy, osquery and endpoint actions continue working.

## Related issues

- Closes https://github.com/elastic/security-team/issues/6501

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Being that this is just disabling it for 8.8.0, I am okay with approving it. But it is somewhat worry some that you were able to completely comment out this code, without having to adjust any tests.

Clearly this code path could use some testing.

**Comment by aleksmaus** [comment]
> But it is somewhat worry some that you were able to completely comment out this code, without having to adjust any tests.

every since piece of protection implementation is covered with it's own unit tests: coverage: 85.2% of statements

the existing policy and actions handlers tests were not expanded to include the policy with the signature, the PR was for the feature was reviewed and approved. more tests were not requested at that time.

can add more tests for the handlers if needed when enabling this feature back for 8.9.0 depending on the product plans.

**Comment by blakerouse** [comment]
> > But it is somewhat worry some that you were able to completely comment out this code, without having to adjust any tests.
> 
> every since piece of protection implementation is covered with it's own unit tests: coverage: 85.2% of statements

That is awesome, great to hear!

> 
> the existing policy and actions handlers tests were not expanded to include the policy with the signature, the PR was for the feature was reviewed and approved. more tests were not requested at that time.

That is not surprising. After EAH we have decided that anything added from now on must come with tests and some type of coverage. Only reason I bring it up.

> 
> can add more tests for the handlers if needed when enabling this feature back for 8.9.0 depending on the product plans.

For it to be re-enabled in 8.9 it would need to be covered, or as a team we will not merge it. We are trying to make that the policy for everything.

**Comment by aleksmaus** [comment]
> For it to be re-enabled in 8.9 it would need to be covered, or as a team we will not merge it. We are trying to make that the policy for everything.

Sounds good. Consider it done.

**Comment by aleksmaus** [comment]
Retested once again with the local agent build on linux ARM with the Endpoint that has the signature validation implemented.

Osquery works:
Screenshot 2023-04-27 at 8 41 53 AM

Changing the policy adding/removing the integrations for Osquery and Endpoint works.

Endpoint actions work:
Screenshot 2023-04-27 at 8 40 07 AM

**Pull request merged**
