### PR TITLE
Bump version to 9.0.0

### PR DESCRIPTION
**Pull request by pierrehilbert**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]

**Comment by jlind23** [comment]
@ycombinator @cmacknz our tests that rely on the previous minor fail most probably because they are looking up for a 9.X and not for 8.16 or 8.17, I think we should force merge anyway.

**Review by gizas — APPROVED** [review]

**Comment by jlind23** [comment]
buildkite test it

**Comment by ycombinator** [comment]
CI errors are due to the `9.0.0-SNAPSHOT` not existing yet, which is expected at this point.  Force merging so we can produce an Elastic Agent `9.0.0` DRA and unified release to solve the 🐔 / 🥚 problem...

**Comment by rdner** [comment]
@ycombinator merging this PR caused compatibility errors from Fleet, see https://buildkite.com/elastic/elastic-agent-extended-testing/builds/2732#0191e1d6-bbe9-44d6-8445-7c408940bde4 for examples.

**Pull request merged**
