### PR TITLE
[helm]: implement support for defining image pull secrets

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## What does this PR do?

This PR that adds support for defining `pullImageSecrets` support in the chart

## Why is it important?

Users mights need to deploy an agent image from a private repository

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

N/A

## How to test this PR locally

```
mage integration:kubernetesMatrix
```

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Looks good.

**Review by swiatekm — APPROVED** [review]
I think it's more idiomatic to attach these to a ServiceAccount instead of the Pod, but in this case it doesn't matter too much.

**Review by andrzej-stencel — APPROVED** [review]

**Comment by pkoutsovasilis** [comment]
> I think it's more idiomatic to attach these to a ServiceAccount instead of the Pod, but in this case it doesn't matter too much.

I don't have a preference of one way (ServiceAccount attachment) over the other (Pod attachment), but since there is this [draft PR](https://github.com/elastic/elastic-agent/pull/5593) (planning on working on that soon) that will allow the users to complete override service accounts I chose the latter to deterministically always apply the `imagePullSecrets` and not allow it to be overidden. 


> Also, can you actually set this in one of the examples?

I can mention it but having it actually in the example cli commands I don't think so as I don't have a guaranteed elastic-agent image under a private registry and I would like to keep the examples as simple as a straight-forward copy-paste. Would that work or you had something else in mind?

**Comment by swiatekm** [comment]
> I can mention it but having it actually in the example cli commands I don't think so as I don't have a guaranteed elastic-agent image under a private registry and I would like to keep the examples as simple as a straight-forward copy-paste. Would that work or you had something else in mind?

That's fine. I mostly just want a sanity check that the template works as expected, but for a change as simple as this one it's not that important.

**Pull request merged**
