### PR TITLE
Reduce agent logs by default

### LINKED ISSUE #4252: Reduce the amount the agent logs by default
**Describe the enhancement:**

We'd like an audit to occur on the current logged messages to make sure that the information at the default INFO log level is useful and is valuable when shipped to Fleet.

**Describe a specific use case for the enhancement or feature:**

10-15% of data produced by Agent is internal logs and metrics, we'd like to reduce the volume of Agent internal monitoring as excessive production of this data consumes significant disk space within customer environments.

**What is the definition of done?**

We have measurably reduced the amount of logs agent generates by default. Ideally we will have reduced agent monitoring log volume by 80% in normal usage and have run out of obvious ideas or superfluous messages to remove.

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?
This PR drops the `Non-zero metrics after 30s...` logs before they get sent to Elasticsearch.

## Why is it important?
The goal is to reduce the amount of elastic-agent monitoring events ingested in Elasticsearch in order to reduce index disk size.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~

## Author's Checklist

- [ ]

## How to test this PR locally
Run an elastic agent with and without this change on a deployment making a note of the start times and elastic-agent id of both.
Using the included ES script we then extract the documents ingested during those runs and store them in dedicated indices.

In my tests I ran 2 elastic agents managed by fleet with a default policy including system integration, first without this change and then including this change, then sliced the first 10 minutes of logs and metrics from startup using the included script.

This is a screenshot from the Index management page were we can see the disk sizes and document count for each index:
Screenshot 2024-05-02 at 18-48-16 Index Management - Elastic

The measured impact on `*logs-elastic_agent.filebeat*` and `*logs-elastic_agent.metricbeat*` is:
- reduction of ~27% of document count for `*logs-elastic_agent.filebeat*` with a disk size reduction of ~18%
- reduction of ~21% of document count for `*logs-elastic_agent.metricbeat*` with a disk size reduction of ~16% 

## Related issues

- Relates #4252 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by amitkanfer** [comment]
@pchila does this really close #4252 ? or only address [this](https://github.com/elastic/elastic-agent/issues/4252#issuecomment-2057428599) suggestion by @cmacknz ?

**Comment by pchila** [comment]
> @pchila does this really close #4252 ? or only address [this](https://github.com/elastic/elastic-agent/issues/4252#issuecomment-2057428599) suggestion by @cmacknz ?

At this stage it addresses @cmacknz 's suggestion and removes some unnecessary logs, not sure if we want to stop here for this PR or we are going deeper, it depends on the measurement of how much data we are saving as it is and general 8.14 timeframe... Will change the "Closes" to "Relates"

**Comment by pierrehilbert** [comment]
I agree here, we shouldn't try to close https://github.com/elastic/elastic-agent/issues/4252 but try to get as many improvement as possible for 8.14 and then continue for the next versions what we won't have time to do in that timeframe.

**Review by cmacknz — APPROVED** [review]
I enrolled an agent built from this branch and observed 30s metrics in the local agent logs but not in Fleet as expected.

**Comment by pierrehilbert** [comment]
@cmacknz any objections with backporting this in 8.14?

**Comment by cmacknz** [comment]
No objections to backporting.

**Pull request merged**
