### PR TITLE
internal/pkg/agent/application/coordinator: fix logging calls

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

Fixes logging calls that expect to be able to interpret formatting verbs.

## Why is it important?

Current code is incorrect.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Nice catch!

**Comment by blakerouse** [comment]
buildkite test this

**Comment by efd6** [comment]
@blakerouse Are you able to force merge this? The integration tests are failing for unrelated reasons.

**Comment by cmacknz** [comment]
Merging, seems like the Windows tests aborted themselves without explanation, I do see the Linux tests passed.

```
2023-11-14 23:27:48 UTC | >>> (linux-amd64-ubuntu-2204) Test output (sudo) (stdout): >> go test: remote-linux-amd64-ubuntu-2204-sudo.integration Test Passed
-- | --
  | 2023-11-15 03:24:36 UTC | >>> (windows-amd64-2022) non-sudo tests failed: wait: remote command exited without exit status or exit signal
  | 2023-11-15 03:24:36 UTC | >>> (windows-amd64-2022) Failed to execute tests on instance: error running non-sudo tests: failed to fetched test output at %home%\agent\build\TEST-go-remote-windows-amd64-2022.integration.out
```

**Pull request merged**
