### PR TITLE
soft_fail on integration tests

### PR DESCRIPTION
**Pull request by rowlandgeoff**
Enable soft_fail on the integration test pipeline steps to temporarily work around the issue in https://elastic.slack.com/archives/C047NDNGUMU/p1727087616173239

Rel: https://github.com/elastic/ingest-dev/issues/4082

### CODE REVIEW

**Comment by rowlandgeoff** [comment]
Hmm, this didn't work as expected. CI is still failing.

**Comment by ycombinator** [comment]
@rowlandgeoff I think we can close this PR unmerged now, since we've diagnosed the root cause of Agent CI failures?

**Comment by rowlandgeoff** [comment]
> @rowlandgeoff I think we can close this PR unmerged now, since we've diagnosed the root cause of Agent CI failures?

@ycombinator I left it as a draft for safety, and was planning to close it tomorrow once we confirm the agent pipeline is fixed. Plus I'm still testing one piece of it.

**Comment by rowlandgeoff** [comment]
Confirming the soft_fail works now. But hopefully this PR won't be needed.

**Comment by rowlandgeoff** [comment]
Closing now that the dependency issue with beats and the unified release has been resolved.

**Pull request closed without merging**
