### PR TITLE
Add assetbeat as external component

### PR DESCRIPTION
**Pull request by girodav**
## What does this PR do?

Add `assetbeat` among the external build dependencies.

## Why is it important?

`assetbeat` is a new binary designed for collecting infrastructure assets. It is intended to be included in the 8.11 release and bundled with Elastic Agent. Although the necessary steps to publish DRAs and create a filespec for assetbeat have already been completed, this particular change was inadvertently missed.

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Relates https://github.com/elastic/obs-infraobs-team/issues/1114
- Relates https://github.com/elastic/release-eng/issues/725

### CODE REVIEW

**Review by MichaelKatsoulis — APPROVED** [review]

**Review by jlind23 — APPROVED** [review]

**Comment by jlind23** [comment]
Buildkite test this

**Comment by jlind23** [comment]
@pchila is this apm integration test failure the same you have spotted on another PR?

**Comment by pchila** [comment]
@jlind23 yes, those are the same failures we see on main. It seems that the cloud stack 8.11.0-SNAPSHOT has some issues with APM server endpoint. I will prepare a PR to use 8.10.2 version to get the CI  green and contact apm team about this

**Comment by girodav** [comment]
buildkite test this

**Review by pierrehilbert — APPROVED** [review]

**Pull request merged**
