### PR TITLE
[CI] Automatic retries for integration tests

### PR DESCRIPTION
**Pull request by pazone**
## What does this PR do?
Each failed integration test step will be retried once

## Why is it important?
Sometimes the tests are flaky. It's not the best practice but anyway we retry them manually 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Closes https://github.com/elastic/ingest-dev/issues/3568

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by michalpristas — APPROVED** [review]
limit 1 means, 1 failure will be retried right?

**Comment by pazone** [comment]
> limit 1 means, 1 failure will be retried right?

It means it will be retried only once

**Comment by jlind23** [comment]
Looks like this retry was meant to be only for OGC task according to the issue right?

**Comment by rdner** [comment]
@jlind23 If I understand the diff correctly, now Buildkite retries every integration test step (Serverless integration test, Extended runtime leak tests, Integration tests, Serverless Beats Tests) if it fails, regardless the cause. Correct me if I'm wrong.

**Comment by jlind23** [comment]
No you are right, I don't think this was the intent behind https://github.com/elastic/ingest-dev/issues/3568 according to the description wrote by @dli

**Comment by dliappis** [comment]
> No you are right, I don't think this was the intent behind [elastic/ingest-dev#3568](https://github.com/elastic/ingest-dev/issues/3568) according to the description wrote by @dliappis

yes the intent was to retry OGC tasks only, as work around to out of capacity issues in an AZ e.g. https://buildkite.com/elastic/elastic-agent-extended-testing/builds/1323#0190a43f-e423-470c-b73e-82a428a451dd/567-638
A well tested approach outside of BK (implemented e.g. in the corresponding tool used by elasticsearch performance) is that the tool itself (ogc) rotates across eligible AZs in the region, when there is an out of capacity issue (in addition to retries for a specific AZ).

**Comment by pazone** [comment]
@dliappis @rdner If the BK retries are that bad idea I can revert it and reopen the initial issue

**Comment by rdner** [comment]
reverted by https://github.com/elastic/elastic-agent/pull/5170

**Pull request merged**
