### PR TITLE
Increase watcher in upgrade tests to timeout after 10m

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Increase the timeout we wait for the watcher to stop to 10m from 1m.

## Why is it important?

7.17.23 has a regression where it will upgrade an 8.x release then roll back after a few minutes. 
The expected fix is https://github.com/elastic/beats/pull/40452 which will affect 7.17.24.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Relates #5259

### CODE REVIEW

**Comment by blakerouse** [comment]
@michel-laterman Seems the change did cause it to fail, so that is a good sign.

**Comment by blakerouse** [comment]
Seems we should merge https://github.com/elastic/beats/pull/40452 and wait for next snapshot to validate that it only fails on 7.17.23 and no longer 7.17.24-SNAPSHOT.

Need a +1 on https://github.com/elastic/beats/pull/40452 for merge.

**Comment by michel-laterman** [comment]
@blakerouse do we want to revert the changes I made to `upgrader.go` or should we keep them in case there is a regression?

**Review by blakerouse — APPROVED** [review]
@michel-laterman Being that the watcher always reads the configuration to lower the timeout, I think its best to keep your change of the timeouts in the PR. This now means it will only slow the tests down in the case there is a regression and we would rather have that then miss a regression.

**Pull request merged**
