### PR TITLE
Add pprofextension from the OTel-contrib

### PR DESCRIPTION
**Pull request by alexsapran**
## What does this PR do?

This comit adds the pprofextension to the OTel collector.

## Why is it important?

As part of running benchmarks for Elastic-Agent we need to be able to take diagnostic profiles and as we onboard the OTel collector to the framework we need to enable Pprof for the OTel collector.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## How to test this PR locally

Once you have a packaged version of Elastic-Agent then you can start it with the following OTel config

```yaml 
#.... other stuff....
extensions:
    pprof:
        endpoint: localhost:5066
#... some other....
service:
    extensions:
        - pprof
    #.. other extensions

```

## Related issues

- Relates: https://github.com/elastic/ingest-dev/issues/4027

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by swiatekm — APPROVED** [review]

**Review by blakerouse — APPROVED** [review]
+1

**Comment by ycombinator** [comment]
I removed the `backport-skip` label and added the `backport-8.x` label.  Unless a PR introduces a breaking change intended for `9.0.0`, we should backport the PR to the `8.x` branch.

**Comment by alexsapran** [comment]
thanks @ycombinator , i had added the skip because i was not sure if we would like to backport it or not. Since we are +1 with adding it, then backports make sense, and thanks

**Pull request merged**
