### PR TITLE
switch to consistent HasRoot method on windows and fix memory leak

### PR DESCRIPTION
**Pull request by leehinman**
## What does this PR do?

replaces custom `isWindowsAdmin` in listener_windows.go with call to `HasRoot` implementation in `utils`.  Also fix memory leak in `HasRoot` function.

## Why is it important?

In some localized Windows installs calls to `GroupIds` for the user of the process fail, this was causing the `isWindowsAdmin` check to fail, which causes problems with the control socket for `elastic-agent`.

The `HasRoot` implementation doesn't depend on `GroupIds`

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

### Prior to this PR.

1. Run agent install command on Windows 10 French/German VM.
2. Observe agent service is not restarted itself on installation.
3. Navigate to services and manually restart the Elastic Agent service.
4. Observe agent gets Healthy under Agents tab.

### With this PR

1. Run agent install command on Windows 10 French/German VM.
2. Observe agent service is restarted on installation.
3. `elastic-agent restart` should work

## Related issues

- #3960

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by pierrehilbert** [comment]
Failure seems to be unrelated (your change is impacting windows only and the failure is on Ubuntu).
I created an issue for this failure: https://github.com/elastic/elastic-agent/issues/3989

**Review by blakerouse — COMMENTED** [review]
Does this have the same semantics? Will this allow a user that is part of the Administrators group to still be able to communicate with the Elastic Agent control socket?

**Comment by leehinman** [comment]
> Does this have the same semantics? Will this allow a user that is part of the Administrators group to still be able to communicate with the Elastic Agent control socket?

yes.  take a look at https://github.com/golang/go/issues/28804 for more in depth discussion.  But basically the check is to see if the current process is part of the "well known" admin SID, and if so then the Administrators group gets added to the control socket.  None of the logic changed about adding to the security descriptor on the socket, just in how we detect if the process is "Admin" or not.

**Review by blakerouse — APPROVED** [review]
Thanks for the details. Awesome!

**Review by michalpristas — APPROVED** [review]

**Pull request merged**
