### PR TITLE
Small fixes and improvements on non production code

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Small changes improving name consistency and error reporting on mage tools and the testing framework

## Why is it important?

It avoids the need to go through the code to understand why an error happened or why something does not behaves as expected.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

Use `mage integration:single` to run a test that fail the build. Now you can see the error, not just "build failed"

## Related issues

- N/A

## Logs

Before:
```
Error: failed to detemine batches: error running go test: (exit status 1), got: FAIL	github.com/elastic/elastic-agent/testing/integration [build failed]
, tried to run: [go test -v --tags integration,define -json ./testing/integration]
```

Now:
```
Error: failed to determine batches: error running go test: (exit status 1), got:

# github.com/elastic/elastic-agent/testing/integration [github.com/elastic/elastic-agent/testing/integration.test]
testing/integration/proxy_url_test.go:40:2: agentVersion declared and not used
FAIL	github.com/elastic/elastic-agent/testing/integration [build failed]

tried to run: [go test -v --tags integration,define -json ./testing/integration]
```

### CODE REVIEW

**Review by belimawr — APPROVED** [review]

**Review by pierrehilbert — APPROVED** [review]
Trusting @belimawr's review here to unlock @AndersonQ

**Comment by ycombinator** [comment]
When `EnrollElasticAgent` was renamed to `InstallElasticAgent` and similarly `EnrollElasticAgentWithPolicy` was renamed to `InstallElasticAgentWithPolicy`, it's callers were not updated to match.  So now there is test code that's not compiling any more 😞. 

```
testing/integration/fqdn_test.go:103:23: undefined: tools.EnrollAgentWithPolicy
testing/integration/upgrade_test.go:118:23: undefined: tools.EnrollElasticAgent
FAIL	github.com/elastic/elastic-agent/testing/integration [build failed]
```

We need to get these tests running in CI to catch such errors in PRs but, until then, let's please run these tests manually.  Also, to be safe, we should probably use IDE refactoring tooling for such renames so occurrences are not missed.

**Comment by pierrehilbert** [comment]
Sorry for that @ycombinator
You suggested to fix this by yourself (thanks) but we should be more careful, thanks for the reminder.

**Comment by ycombinator** [comment]
PR to fix https://github.com/elastic/elastic-agent/pull/2833#issuecomment-1584882967 is up: https://github.com/elastic/elastic-agent/pull/2837

**Pull request merged**
