### PR TITLE
Remove artifacts from deprecated Elastic Endpoint in K8s project

### PR DESCRIPTION
**Pull request by norrietaylor**
## What does this PR do?

The Elastic Endpoint in K8s project has been deprecated. This PR cleans up artifacts that remained in the Agent YAML due to that project.  

This PR is tested in the cloud-defend CI pipeline.

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]
Thanks!

**Comment by gizas** [comment]
The node autodiscovery of elastic agent is based (in one of the alternatives) to machine-id: https://github.com/elastic/elastic-agent-autodiscover/blob/e3da20d82e3f0fa03637f298d73d631cbd9b0068/kubernetes/util.go#L198

So the mounting of this `/etc/machine-id` is needed and not to be removed

**Review by gizas — CHANGES_REQUESTED** [review]
See comment https://github.com/elastic/elastic-agent/pull/4081#issuecomment-1891512435

**Comment by pierrehilbert** [comment]
@norrietaylor what is the plan with this PR? Still relevant?

**Comment by norrietaylor** [comment]
This certainly slipped through the cracks. Apologies. 

This is clean up, that we should probably do, as the Elastic Defend integration in K8s is no longer supported or distributed. 

I made the changes requested by @gizas and @MichaelKatsoulis. If they give the LGTM, we can merge.

**Review by gizas — APPROVED** [review]

**Pull request merged**
