### PR TITLE
add process dump after failed install

### LINKED ISSUE #4935: [Integration Test Framework] Dump process list on first failure
Currently, when an integration test fails, we dump the process list to help debug the failure, by registering a `t.Cleanup()` callback: https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/pkg/testing/fixture_install.go#L219-L226

However, this callback registration is happening after the test attempts to install Elastic Agent: https://github.com/elastic/elastic-agent/blob/e8962b0e4857f1e66d5b4887b4c8fcbb4f1e8af0/pkg/testing/fixture_install.go#L180-L194

Consequently, if the install itself fails, we do not get a dump of the process list.  

We should make it so the process list is dumped on the earliest failure of any integration test.

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?

This PR adds a process dump to be taken just after the elastic-agent install fails. It is related to failures we see in the integration tests similar to 

```json
        {"log.level":"info","@timestamp":"2024-06-12T18:03:34.276Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":518},"message":"Starting enrollment to URL: http://localhost:50163/","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-06-12T18:03:35.147Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":481},"message":"Restarting agent daemon, attempt 0","ecs.version":"1.6.0"}
        {"log.level":"error","@timestamp":"2024-06-12T18:03:35.150Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":495},"message":"Restart attempt 0 failed: 'rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: open \\\\\\\\.\\\\pipe\\\\elastic-agent-system: The system cannot find the file specified.\"'. Waiting for 2s","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-06-12T18:03:37.160Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":481},"message":"Restarting agent daemon, attempt 1","ecs.version":"1.6.0"}
        {"log.level":"error","@timestamp":"2024-06-12T18:03:37.161Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":495},"message":"Restart attempt 1 failed: 'rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: open \\\\\\\\.\\\\pipe\\\\elastic-agent-system: The system cannot find the file specified.\"'. Waiting for 4s","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-06-12T18:03:41.168Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":481},"message":"Restarting agent daemon, attempt 2","ecs.version":"1.6.0"}
        {"log.level":"error","@timestamp":"2024-06-12T18:03:41.169Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":495},"message":"Restart attempt 2 failed: 'rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: open \\\\\\\\.\\\\pipe\\\\elastic-agent-system: The system cannot find the file specified.\"'. Waiting for 8s","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-06-12T18:03:49.169Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":481},"message":"Restarting agent daemon, attempt 3","ecs.version":"1.6.0"}
        {"log.level":"error","@timestamp":"2024-06-12T18:03:49.170Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":495},"message":"Restart attempt 3 failed: 'rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: open \\\\\\\\.\\\\pipe\\\\elastic-agent-system: The system cannot find the file specified.\"'. Waiting for 16s","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-06-12T18:04:05.171Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":481},"message":"Restarting agent daemon, attempt 4","ecs.version":"1.6.0"}
        {"log.level":"error","@timestamp":"2024-06-12T18:04:05.172Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":495},"message":"Restart attempt 4 failed: 'rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: open \\\\\\\\.\\\\pipe\\\\elastic-agent-system: The system cannot find the file specified.\"'. Waiting for 32s","ecs.version":"1.6.0"}
        {"log.level":"error","@timestamp":"2024-06-12T18:04:37.181Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":295},"message":"Elastic Agent might not be running; unable to trigger restart: could not reload agent's daemon, all retries failed. Last error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: open \\\\\\\\.\\\\pipe\\\\elastic-agent-system: The system cannot find the file specified.\"","ecs.version":"1.6.0"}
        Something went wrong while enrolling the Elastic Agent: could not reload agent's daemon, all retries failed. Last error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."
        Error: could not reload agent daemon, unable to trigger restart: could not reload agent's daemon, all retries failed. Last error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."
        For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.15/fleet-troubleshooting.html
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Closes #4935 

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Looks good. Thanks for this improvement.

**Comment by pierrehilbert** [comment]
Can we backport this to 8.14? @pchila

**Comment by pchila** [comment]
We can, although I would prefer to leave 8.14 branch undisturbed as much as possible... Is there a specific reason to have this also on 8.14?

**Comment by pierrehilbert** [comment]
We are still releasing 8.14 so everything that improves our test framework is good to take :-)

**Pull request merged**
