### PR TITLE
Revert: Bundle elastic-agent.app for MacOS… #714

### PR DESCRIPTION
**Pull request by michalpristas**
Reverting this PR as for issue raised here: https://github.com/elastic/elastic-agent/issues/1298

Issue for followup work created here: https://github.com/elastic/elastic-agent/issues/1386

### CODE REVIEW

**Review by aleksmaus — APPROVED** [review]
LGTM

**Comment by aleksmaus** [comment]
The change was breaking for upgrade, but would still work for the clean install and upgrades going forward, if the customer cares about FDA and not much about upgrade via fleet on MacOS from pre-8.5.0 versions.

**Comment by aleksmaus** [comment]
@michalpristas this PR can be closed now, we are not reverting this change on the main branch and this PR https://github.com/elastic/elastic-agent/pull/1401 backports additional fixes that were merged into 8.5.

**Comment by michalpristas** [comment]
closing as fix already landed

**Pull request closed without merging**
