### PR TITLE
Expand extended runtime tests to check for gorutine usage

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?

closes https://github.com/elastic/elastic-agent/issues/4207

## Why is it important?

This expands the extended runtime test to check for gorutine leaks. This more or less borrows the same strategy used by the handle leaks: measure the handle usage at regular intervals, then calculate the rate of change.

This also refactors the runtime test for readability and reusability. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an integration test or an E2E test

### CODE REVIEW

**Comment by cmacknz** [comment]
How did you test that this detects leaks? I hope we don't have any by default :) 

How slow can the leak be before detection of it fails?

**Comment by fearful-symmetry** [comment]
@cmacknz I ended up inadvertently testing this while I was developing it; I forgot to close the unix socket connection, causing both the tests to fail after every call to the status socket spawned a new connection. In general, "the metric under test increasing by one every measurement period" is enough to fail the test.

Should probably find a more reliable way to test this, though. I'll add a bug to the system integration and see what happens.

**Comment by fearful-symmetry** [comment]
So, adding a few lines of code that spins off a goroutine every time `Fetch` is called in a metricset is enough to trigger a failure:
```
>>> (linux-amd64-ubuntu-2204-fleet) Test output (sudo) (stdout): Error:         "1.003423582991148" is not less than or equal to "0.1"
>>> (linux-amd64-ubuntu-2204-fleet) Test output (sudo) (stdout): Test:          TestLongRunningAgentForLeaks/TestHandleLeak
>>> (linux-amd64-ubuntu-2204-fleet) Test output (sudo) (stdout): Messages:      increase in count of gorutines exceeded threshold for system/metrics: system/metrics
```

**Review by michalpristas — COMMENTED** [review]
test makes sense to me. i know finding right balance between false positives and negatives may be difficult, does 0.1 has some buffer so we avoid false failures?

**Comment by fearful-symmetry** [comment]
@michalpristas I haven't gotten a false positive yet with 0.1, most beats will come in a few orders of magnitude less, usually 0.00001 to 0.001.

**Review by michalpristas — APPROVED** [review]

**Pull request merged**
