### PR TITLE
Adjust memory requests and limits for elastic-agent when run in Kubernetes cluster

### PR DESCRIPTION
**Pull request by MichaelKatsoulis**
## What does this PR do?

This PR adjusts the default memory requests and limits for elastic-agent when it runs in a Kubernetes cluster.
The new requests and limits will be
```
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi
```
These will be adequate even in big load (tested with 95 pods per node).

## Why is it important?

In latest elastic-agent versions the baseline memory consumption is higher, thus adding Kubernetes and system
integration leads to often OOM killed pods.
The previous memory limit set was 700Mb

After investigation with various number of pods we have seen that in ^8.15.* versions 
the memory consumption can reach from 750 to 950 Mb.
This varies depending on the number of pods a single elastic agent has to monitor.
For example:
```
45 pods per node: mem consumption up to 810 MB
60  pods per node: mem consumption up to 830 Mb
75 pods per node: mem consumption up to 930 Mb
95 pods per node: mem consumption up to 990 MB
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Disruptive User Impact

The inadequate memory limits lead to elastic-agent getting often OOM killed in newer versions.

## How to test this PR locally

Deploy Elastic Agent with system and Kubernetes integration following the Kibana instructions and watch the
memory consumption of the pod with `watch "kubectl top pod -n kube-system" ` and its status.

## Related issues

- Relates https://github.com/elastic/elastic-agent/issues/5613
- Relates https://github.com/elastic/elastic-agent/issues/4729

### CODE REVIEW

**Review by gizas — APPROVED** [review]

**Review by pkoutsovasilis — COMMENTED** [review]
Hey @MichaelKatsoulis 👋 could you check the failures in CI? I think that some other files also need the change of the limits

**Review by tetianakravchenko — APPROVED** [review]

**Review by pkoutsovasilis — APPROVED** [review]

**Comment by MichaelKatsoulis** [comment]
@pchila do you have any idea why these build kite integrations tests are failing?  It is not obvious to me.
The only updates to this PR are the slight increase of memory requests and  limits in elastic agent in Kubernetes.

**Comment by MichaelKatsoulis** [comment]
@pchila I pulled you in cause it seemed to me that you have worked a lot with those failing integrations tests. Thanks for your time and information.

**Pull request merged**
