### PR TITLE
Bump elastic-agent-autodiscover version

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## What does this PR do?

To include fix introduced in elastic-agent-autodiscover by this PR - https://github.com/elastic/elastic-agent-autodiscover/pull/72

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by pierrehilbert** [comment]
Could you please add a changelog to mention what it will bring?

**Comment by cmacknz** [comment]
Please add a changelog fragment https://github.com/elastic/elastic-agent?tab=readme-ov-file#changelog

**Review by cmacknz — APPROVED** [review]

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
Test failures are an unrelated known issue, force merging.

**Comment by tetianakravchenko** [comment]
> Test failures are an unrelated known issue, force merging.

hey @cmacknz coult you please help with the backporting PRs? I think there are the same unrelated issues

**Pull request merged**
