### PR TITLE
Fix TestWriteMarkerFileWithTruncation flaky test

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Fixes TestWriteMarkerFileWithTruncation flaky test
Addresses [Flaky Test TestMarkerWatcher](https://github.com/elastic/elastic-agent/issues/3981) 

This is one way to fix this without rewriting the test too much.

The actual problem is in the TestWriteMarkerFileWithTruncation test, which also corresponds with the stack trace in the original issue.

There are few problems with that tests:
1. Race condition between Go routines that this tests starts upon the cancelling the shared context. 
Need to wait for the watcher to exit first, and only then exit from the Go routine that listens on  errCh (otherwise the watcher Go routine that writes into errCh can get blocked and leak).
https://github.com/aleksmaus/elastic-agent/blob/main/internal/pkg/agent/application/upgrade/marker_access_test.go#L44
Only after that close the errCh.

2. Another issue was not breaking out on the error case here https://github.com/aleksmaus/elastic-agent/blob/main/internal/pkg/agent/application/upgrade/marker_access_test.go#L124, that would cause double write into unbuffered errCh.

## Why is it important?

Test stability

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Related issues

- Closes https://github.com/elastic/elastic-agent/issues/3981

### CODE REVIEW

**Review by ycombinator — APPROVED** [review]
LGTM - thanks for adding the missing synchronization and the missed `return` as well.

**Comment by aleksmaus** [comment]
Unrelated test failure:
```
>>> (linux-arm64-ubuntu-2204-default) Test output (non-sudo) (stdout): === FAIL: testing/integration TestAPMConfig (22.82s)
```

**Review by blakerouse — APPROVED** [review]

**Comment by blakerouse** [comment]
How does this solve #3981?

**Comment by aleksmaus** [comment]
> How does this solve #3981?

I mentioned that in this comment
https://github.com/elastic/elastic-agent/issues/3981#issuecomment-1874386321

**Comment by blakerouse** [comment]
@aleksmaus Thanks, missed that comment on the issue.

**Pull request merged**
