### PR TITLE
Add breakdown of tests output for integration testing framework

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Adds a `mage integration:breakdown` and `mage integration:breakdownMatrix` targets that write an intermediate output of the list of operating systems and which tests need to run on each version of those operating systems.

## Why is it important?

Allows an easy way to see which tests run on which os/arch/distro/version combinations, along with if a stack is required and if the test needs the stack or not.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Disruptive User Impact

None

## How to test this PR locally

`mage integration:breakdown`

or

`mage integration:breakdownMatrix`

## Enable output

```
- name: fqdn-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
  require_sudo: true
  tests:
    - TestFQDN
- name: kubernetes
  os:
    - type: kubernetes
      arch: amd64
      version: 1.31.0
      docker_variant: service
    - type: kubernetes
      arch: arm64
      version: 1.31.0
      docker_variant: service
    - type: kubernetes
      arch: amd64
      version: 1.31.0
      docker_variant: basic
    - type: kubernetes
      arch: arm64
      version: 1.31.0
      docker_variant: basic
    - type: kubernetes
      arch: amd64
      version: 1.31.0
      docker_variant: wolfi
    - type: kubernetes
      arch: arm64
      version: 1.31.0
      docker_variant: wolfi
    - type: kubernetes
      arch: amd64
      version: 1.31.0
      docker_variant: ubi
    - type: kubernetes
      arch: arm64
      version: 1.31.0
      docker_variant: ubi
    - type: kubernetes
      arch: amd64
      version: 1.31.0
      docker_variant: complete
    - type: kubernetes
      arch: arm64
      version: 1.31.0
      docker_variant: complete
    - type: kubernetes
      arch: amd64
      version: 1.31.0
      docker_variant: complete-wolfi
    - type: kubernetes
      arch: arm64
      version: 1.31.0
      docker_variant: complete-wolfi
  require_sudo: false
  tests: []
- name: deb-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
  require_sudo: true
  tests:
    - TestDebLogIngestFleetManaged
    - TestDebFleetUpgrade
- name: rpm-sudo
  os:
    - type: linux
      arch: amd64
      version: "8"
      distro: rhel
    - type: linux
      arch: arm64
      version: unknown
      distro: rhel
  require_sudo: true
  tests:
    - TestRpmLogIngestFleetManaged
    - TestRpmFleetUpgrade
- name: fleet-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
    - type: windows
      arch: amd64
      version: "2022"
    - type: darwin
      arch: amd64
      version: unknown
      distro: unknown
    - type: darwin
      arch: arm64
      version: unknown
      distro: unknown
  require_sudo: true
  tests:
    - TestLongRunningAgentForLeaks
    - TestDelayEnroll
    - TestDelayEnrollUnprivileged
    - TestRedactFleetSecretPathsDiagnostics
    - TestInstallAndCLIUninstallWithEndpointSecurity
    - TestInstallAndUnenrollWithEndpointSecurity
    - TestInstallWithEndpointSecurityAndRemoveEndpointIntegration
    - TestEndpointSecurityNonDefaultBasePath
    - TestEndpointSecurityUnprivileged
    - TestEndpointSecurityCannotSwitchToUnprivileged
    - TestEndpointLogsAreCollectedInDiagnostics
    - TestForceInstallOverProtectedPolicy
    - TestInspect
    - TestSetLogLevelFleetManaged
    - TestLogIngestionFleetManaged
    - TestMetricsMonitoringCorrectBinaries
    - TestEndpointAgentServiceMonitoring
    - TestMonitoringPreserveTextConfig
    - TestMonitoringLivenessReloadable
    - TestComponentBuildHashInDiagnostics
    - TestProxyURL
    - TestFleetManagedUpgradeUnprivileged
- name: default
  os:
    - type: darwin
      arch: amd64
      version: unknown
      distro: unknown
    - type: darwin
      arch: arm64
      version: unknown
      distro: unknown
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
    - type: windows
      arch: amd64
      version: "2022"
  require_sudo: false
  tests:
    - TestInstallWithoutBasePath
    - TestInstallWithBasePath
    - TestInstallPrivilegedWithoutBasePath
    - TestInstallPrivilegedWithBasePath
    - TestInstallUninstallAudit
    - TestRepeatedInstallUninstall
    - TestSwitchPrivilegedWithoutBasePath
    - TestSwitchPrivilegedWithBasePath
    - TestSwitchUnprivilegedWithoutBasePath
    - TestSwitchUnprivilegedWithBasePath
    - TestBeatsServerless
- name: container-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
  require_sudo: true
  tests:
    - TestContainerCMD
    - TestContainerCMDWithAVeryLongStatePath
    - TestContainerCMDEventToStderr
    - TestEventLogOutputConfiguredViaFleet
- name: fleet-privileged-sudo
  os:
    - type: darwin
      arch: amd64
      version: unknown
      distro: unknown
    - type: darwin
      arch: arm64
      version: unknown
      distro: unknown
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
    - type: windows
      arch: amd64
      version: "2022"
  require_sudo: true
  tests:
    - TestInstallFleetServerBootstrap
    - TestFleetManagedUpgradePrivileged
- name: upgrade-sudo
  os:
    - type: darwin
      arch: amd64
      version: unknown
      distro: unknown
    - type: darwin
      arch: arm64
      version: unknown
      distro: unknown
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
    - type: windows
      arch: amd64
      version: "2022"
  require_sudo: true
  tests:
    - TestUpgradeBrokenPackageVersion
    - TestStandaloneUpgradeWithGPGFallback
    - TestStandaloneUpgradeWithGPGFallbackOneRemoteFailing
    - TestStandaloneUpgradeRollback
    - TestStandaloneUpgradeRollbackOnRestarts
    - TestStandaloneUpgradeFailsWhenUpgradeIsInProgress
    - TestStandaloneUpgradeRetryDownload
    - TestStandaloneUpgradeSameCommit
    - TestStandaloneUpgrade
    - TestStandaloneUpgradeUninstallKillWatcher
- name: fleet-airgapped-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
  require_sudo: true
  tests:
    - TestFleetAirGappedUpgradeUnprivileged
- name: fleet-airgapped-privileged-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
  require_sudo: true
  tests:
    - TestFleetAirGappedUpgradePrivileged
- name: fleet-upgrade-to-pr-build-sudo
  os:
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
  require_sudo: true
  tests:
    - TestFleetUpgradeToPRBuild
- name: default-sudo
  os:
    - type: darwin
      arch: amd64
      version: unknown
      distro: unknown
    - type: darwin
      arch: arm64
      version: unknown
      distro: unknown
    - type: linux
      arch: amd64
      version: "24.04"
      distro: ubuntu
    - type: linux
      arch: arm64
      version: "24.04"
      distro: ubuntu
    - type: windows
      arch: amd64
      version: "2022"
  require_sudo: true
  tests:
    - TestInstallWithoutBasePath
    - TestInstallWithBasePath
    - TestInstallPrivilegedWithoutBasePath
    - TestInstallPrivilegedWithBasePath
    - TestInstallUninstallAudit
    - TestRepeatedInstallUninstall
    - TestSwitchPrivilegedWithoutBasePath
    - TestSwitchPrivilegedWithBasePath
    - TestSwitchUnprivilegedWithoutBasePath
    - TestSwitchUnprivilegedWithBasePath
    - TestBeatsServerless
```

### CODE REVIEW

**Comment by pchila** [comment]
I understand that what you added in the description of the PR is the output of the new mage target, but maybe we can discuss the structure of the output a bit since there are bits that may benefit from further polishing

1. Simple linux test description:
```yaml
  - id: linux-amd64-ubuntu-2404-default
    os:
      type: linux
      arch: amd64
     version: "24.04"
      distro: ubuntu
    batch:
      group: default
      stack:
          version: 9.0.0-SNAPSHOT
      tests:
          - name: github.com/elastic/elastic-agent/testing/integration
            tests:
              - name: TestAPMConfig
                stack: true
              - name: TestDiagnosticsOptionalValues
                stack: false
             ...
              - name: TestPackageVersion
                stack: false
      sudo_tests:
          - name: github.com/elastic/elastic-agent/testing/integration
            tests:
              - name: TestBeatsServerless
                stack: true
              - name: TestInstallWithoutBasePath
                stack: false
             ...
              - name: TestSwitchUnprivilegedWithBasePath
                stack: false
```
-  Is it possible to extract OS type and arch to a `platform` layer that groups all the tests for a given platform? Similar to the concept we already use in magefile ?
-  Can we change the `distro` attributes of OS with just `name` (distro is very linux-specific attribute and at the end of the day is just the name of a specific linux OS we require)? Using `name` may open the way of specifying different windows variants should we need to...
-  Do we always require ubuntu in all non rhel/deb tests ? I assume that for most of the tests we don't care which linux distribution is used as long as we can install elastic-agent using the `.tar.gz` archive
-  `sudo_test` vs `test`: shouldn't this be a boolean value if a test requires sudo to be run? (such tests seem to be the majority)
  
2. K8s test description:
```yaml
  - id: kubernetes-amd64-1310-basic-kubernetes
  os:
    type: kubernetes
    arch: amd64
    version: 1.31.0
    docker_variant: basic
  batch:
    group: kubernetes
    stack:
        version: 9.0.0-SNAPSHOT
    tests:
        - name: github.com/elastic/elastic-agent/testing/integration
          tests:
          
```
How is `docker_variant` an attribute of OS in this case? Isn't it just a specific elastic-agent artifact we want to test? Maybe we need to formalize what artifact a given test requires?
Having an OS with `type: kubernetes` also looks a bit strange, maybe we should move the kubernetes in another package with different definitions that will test only on k8s clusters?

I know that the proposed format is what the integration framework currently use internally but his may be an opportunity to clean up the structure a bit and I hope we can work a bit on that

**Comment by blakerouse** [comment]
Every question you proposed is possible, just need a format to be designed that you deam acceptable to reflect your questions. Based on the way your questions are worded you have a design in-mind, please propose it.

The current format is the format I designed for the internal representation of the testing framework, it makes sense to me and to me is very easy to understand. I don't think me spending time on designing a different one is going to provide the result you are looking for, as you already have one in mind.

There is also another format that is a layer up that doesn't add the `ubuntu` and OS version information unless the test specifically requires it. This layer is after items have been batched together and placed on a target, but that allows the `matrix: true` to occur.

Please provide a recommended layout that you find more appropriate and I am sure this output can be transformed into that output.

**Comment by ycombinator** [comment]
@pazone since your code will ultimately be consuming the output being produced by the code in this PR, please post the ideal output that you'd like to see.  You can use the output posted in this PR's description as a starting point and take a look at the discussion in the last couple of comments as well for any ideas.

Once we have your desired output, that will serve as the interface between the integration testing framework and your BK pipeline generator code, and @blakerouse can make tweaks to the code in this PR as needed to produce that output.

**Comment by pazone** [comment]
The ideal output would be
`mage -v integration:breakdown "fleet" "sudo"` and `|`-separated list of the tests like: 

```
TestAPMConfig|TestAnotherThing
```
It will be consumed by `go test`

The OS/ARCH/Version can be determined automatically because we run it on the target VM. This allows us to use matrix step representation

**Comment by ycombinator** [comment]
@pazone We need to agree on the exact output as it will serve as the contract between the integration testing framework and your BK pipeline generator code.  Could you please provide a **complete sample** of the ideal output, similar to what @blakerouse has provided in this PR's description?  Feel free to use that as a starting point and tweak it.  This way, there will be no ambiguity about the contract.  Thanks.

**Comment by pazone** [comment]
@ycombinator The `|`-separated list of tests is required for `gotest`. That's what we need.
```
TestAPMConfig|TestAnother|...
```

**Comment by blakerouse** [comment]
@ycombinator @pazone I have updated this PR to match the discussed format during the meeting. I have updated the output in the PR description to show the updated output.

**Comment by pazone** [comment]
@blakerouse @ycombinator I creating a filter for the tests. Thanks

**Comment by pazone** [comment]
Do I understand correctly that `container-sudo` runs on Unubtu VMs, not containers?

**Comment by ycombinator** [comment]
> Do I understand correctly that `container-sudo` runs on Unubtu VMs, not containers?

Yes, your understanding is correct.  The tests in that group are all running `elastic-agent container` which is the entrypoint command when Elastic Agent is run inside a container.

**Comment by ycombinator** [comment]
> I need the current OS info in this format for filtering:
> 
> ```
> - type: linux
>    arch: amd64
>    version: "24.04"
>    distro: ubuntu
> ```

@pazone The format you posted looks identical to the format in this PR's (updated) description:

> ```
>     - type: linux
>       arch: amd64
>       version: "24.04"
>       distro: ubuntu
> ```

So I'm not sure what you're asking for. 🤔

**Comment by pazone** [comment]
@ycombinator I'm trying to make it work as described here: https://github.com/elastic/elastic-agent/pull/5825#issuecomment-2432160920. To do that, I have to determine current OS facts:
- distro
- version 
- type
- arch

It's not trivial to implement this without using third-party packages. The question is: Have we already implemented anything similar? Maybe I can reuse something?

**Comment by pazone** [comment]
Ok, found this: https://github.com/elastic/go-sysinfo

**Comment by blakerouse** [comment]
Doesn't seem like this is going to get used, closing.

**Pull request closed without merging**
