### PR TITLE
Pre-create `state/` directory inside Docker image to allow writes to named volumes

### PR DESCRIPTION
**Pull request by antoineco**
Type of change: Enhancement

## What does this PR do?

Allows the state directory to be [mounted from a named volume](https://github.com/deviantony/docker-elk/blob/1943f25282082c561072a4705d450b9cfe246a40/extensions/fleet/fleet-compose.yml#L9-L10).

## Why is it important?

Without this change, Docker creates the directory with owner `root:root` (✅) and permissions `0640` (group read-only ❌) while mounting the volume, which prevents the default [`elastic-agent:root`](https://github.com/elastic/elastic-agent/blob/v8.6.1/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl#L143-L145) user/group from writing inside of it.

This approach is also used in the [container image for Elasticsearch](https://github.com/elastic/elasticsearch/blob/4c15cd8a6af2572e69cee48ab6021e31864197b4/distribution/docker/src/docker/Dockerfile#L106) to permit writes to the the `data/` directory.

## How to test this PR locally

1. Create a named volume:

    ```console
    $ docker volume create fleet-state
    fleet-state
    ```

1. Run the elastic-agent image and mount the volume at the location of the `state` directory. Observe that it fails because the `elastic-agent` user doesn't have permissions to write in this directory:

    ```console
    $ docker container run --rm -v fleet-state:/usr/share/elastic-agent/state docker.elastic.co/beats/elastic-agent:8.5.0
    Error: preparing STATE_PATH(/usr/share/elastic-agent/state) failed: mkdir /usr/share/elastic-agent/state/data: permission denied
    ```

1. Build the image with the change from this PR, then run the agent like above, this time with the new image. Observe that the agent starts and populates the `state` directory:

    ```console
    $ docker container run --rm -v fleet-state:/usr/share/elastic-agent/state newimage:latest
    (it works)
    ```

<details><summary>:page_facing_up: Rest of the requested PR information</summary>

## Checklist

- [x] My code follows the style guidelines of this project
- [x] (not applicable) I have commented my code, particularly in hard-to-understand areas
- [x] (not applicable) I have made corresponding changes to the documentation
- [x] (not applicable) I have made corresponding change to the default configuration files
- [x] (not applicable) I have added tests that prove my fix is effective or that my feature works
- [x] (not applicable) I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- 

## Logs

  
</details>

### CODE REVIEW

**Comment by antoineco** [comment]
@cmacknz thanks for triggering the test pipeline! I fixed the typo in [2aa73224..056033f4](https://github.com/elastic/elastic-agent/compare/2aa73224973b07f0c3179a3938bbc51ac753da76..056033f44e99d7749226a7292a72973ff678860a)

**Comment by blakerouse** [comment]
Should add a changelog entry for this change, as I think it is important to highlight.

https://github.com/elastic/elastic-agent/#changelog

**Comment by antoineco** [comment]
@blakerouse I agree. Added in [c36ad886..d36e753e](https://github.com/elastic/elastic-agent/compare/c36ad8867df5f4a6a3c40615b9d028ce1c77cd09..d36e753e27a2b863a4c25e6b53f734809d2da969)

**Comment by antoineco** [comment]
@blakerouse the test keeps failing on the matrix branch `PLATFORM = 'windows-2022 && windows-immutable'`, is there anything I can do about it?

For the time being I'm going to rebase onto `main` and see if it helps.

**Review by blakerouse — APPROVED** [review]
Looks good, thanks for sticking with it!

**Comment by antoineco** [comment]
Doesn't the agent run as `elastic-agent:root`? Besides the directory gets `chmod`ed in the Dockerfile.

**Comment by cmacknz** [comment]
I converted this PR into an issue so it doesn't get lost, this should work even if the first attempt at fixing it didn't quite fix it. 

https://github.com/elastic/elastic-agent/issues/2435

**Pull request merged**
