### PR TITLE
Fix variable names in spec files

### PR DESCRIPTION
**Pull request by faec**
Some spec files have `preventions` fields referencing the nonexistent variable `runtime.user.root`. The correct variable name is `user.root`; presumably this was a typo that got copy-pasted between them. These preventions fields currently have no effect. This PR updates them with the correct name.

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] ~~I have added an integration test or an E2E test~~

## How to test this PR locally

Run Agent with the relevant components, with and without root; before this PR it doesn't produce the configured error message, and afterwards it does. Alternatively (especially on a platform like Mac that requires root to even start), add the negated condition `${runtime.user.root} == true` to any component, and observe that the component still starts without a problem, whereas `${user.root} == true` correctly logs the configured error message.

### CODE REVIEW

**Comment by cmacknz** [comment]
Thanks for finding this. We are planning to add an additional condition here soon (https://github.com/elastic/elastic-agent/issues/2599) so this and the other associated problems will save us some trouble now that they're known.

We need a way to test this. I don't think we have the capability to test with the agent as root yet, but I suspect we can get a test that would have failed because of the invalid variable definition. 

I think that would require us to also fix one or multiple of the other related issues as well:
- [ ] https://github.com/elastic/elastic-agent/issues/2608
- [ ] https://github.com/elastic/elastic-agent/issues/2607
- [ ] https://github.com/elastic/elastic-agent/issues/2609

It would also be ideal if we had something as part of the CI process to catch invalid spec files to prevent more of them from being written. That could be a follow up exercise, although there's a chance we already have this and it's just useless because of the bugs above.

**Comment by faec** [comment]
We probably can't literally test as root, but we could certainly create tests that run the spec files against explicitly specified variables (so the tests could manually set `user.root` to true and make sure the conditions do the right thing). I think that would be a natural thing to include in a fix for those issues, ideally along with explicit documentation of what variables are available in spec file conditions.

**Review by blakerouse — APPROVED** [review]
Looks good, thanks for identifying it.

I think we should write tests to cover the issues you filed related to this PR, but it should not be endpoint-security specific. We ultimately want these specification files to be owned by each component in there own repository. So I think a specific test that the endpoint-security contains a specific condition is not a test that we should have as a unit test in our code.

**Comment by faec** [comment]
> I think a specific test that the endpoint-security contains a specific condition is not a test that we should have as a unit test in our code.

Well, there are already endpoint-specific tests of the spec files -- when I first made my change, `TestComponents` started failing, because it has a test that verifies the rhel7+arm prevention in `endpoint-security.spec.yml` by checking the resulting error message: https://github.com/elastic/elastic-agent/blob/6d47d9b4951910dc828d862bcf7d7760c5f78a38/pkg/component/component_test.go#L402

Once the root check started being enforced with my change, its error message `"Elastic Agent must be running as root"` took precedence, causing the test to fail, so I had to reorder the preventions so the less specific root check came second.

But I agree that we should add some general tests -- even if we can't check every condition / variable combination, we could make sure the preventions don't reference nonexistent variables, which would have been enough to detect the problem in this case.

**Comment by faec** [comment]
I merged this fix into https://github.com/elastic/elastic-agent/pull/2606, since the changes needed to detect problems in the spec files already broke the tests so this last step can't really be done separately -- closing this one.

**Pull request closed without merging**
