### PR TITLE
Fix Endpoint teardown handling while tamper protection is enabled

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Fixes the issue[ [Windows]: Agent with debug logs set gets unhealthy on removing Elastic Defend when Agent tamper protection is enabled ](https://github.com/elastic/elastic-agent/issues/3233)
The Agent was reported UNHEALTHY for up to 10 mins when the Endpoint Integration was removed from the policy with tamper protection enabled.

The problem is intermittent, depends on timing of state changes during teardown and was very difficult to reproduce. After extensive profiling pinpointed a problem, so here is what was happening:
1. The Agent Runtime Manager stops the service runtime here
https://github.com/elastic/elastic-agent/blob/34ac8f91c5c4046a678afbeac8c471ae2fd50e17/pkg/component/runtime/manager.go#L714
2. Then it blocks waiting for the service to stop
https://github.com/elastic/elastic-agent/blob/34ac8f91c5c4046a678afbeac8c471ae2fd50e17/pkg/component/runtime/manager.go#L723
It basically checks every 200ms waiting for STOPPED state for up to uninstall timeout spec config of 10 mins
3. The tamper protected service runtime is sending an extra "checkin expected" config to Endpoint expecting it to disable tamper protection on teardown, so it can proceed to uninstall and STOPPED state. Endpoint depending on timing was sending one or more checkins back clogging the "watcher" channel with the status updates while the runtime manager is blocked waiting on STOPPED.
4. Eventually when the status STOPPED is set the service runtime can't write to the "watch" channel, gets blocked. So the Agent runtime manager is blocked on waiting for STOPPED status from the service runtime and the service runtime could not send it because the channel is not being read.
5. The runtime manager keeps waiting for up to 10mins (Endpoint uninstall timeout), the Agent goes into UNHEALTHY state. After 10 minutes the wait times out, the STOPPED is processed from the service runtime and the  Agent returns to the healthy state.

Some additional logging during research of the problem that shows the runtime::Manager is timing out in 10 mins waiting for STOPPED state from the service runtime:
```
{"log.level":"info","@timestamp":"2023-08-24T16:10:46.482Z","log.origin":{"file.name":"runtime/manager.go","file.line":772},"message":"runtime::Manager::waitForStopped loop latestState.State: HEALTHY","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-08-24T16:10:46.482Z","log.origin":{"file.name":"runtime/manager.go","file.line":786},"message":"runtime::Manager::waitForStopped loop before timeouts wait","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-08-24T16:10:46.621Z","log.origin":{"file.name":"runtime/manager.go","file.line":789},"message":"runtime::Manager::waitForStopped loop on <-timeoutCh","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-08-24T16:10:46.621Z","log.origin":{"file.name":"runtime/manager.go","file.line":723},"message":"runtime::Manager::update after m.waitForStopped(state), state.id: endpoint-default","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-08-24T16:10:46.744Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":917},"message":"Coordinator::runLoopIteration: <-c.managerChans.configManagerUpdate finished: change: &{0xc0005aa050 0xc0005dba10 0xc000d737d0 0xc0001131e8 true <nil>}","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

The solution is to ignore the intermediate checkins/status updates from the service runtime during teardown sequence. Also, after the service runtime is stopped there should be no more state observed updates sent to the "watch" channel, otherwise the `sendObserved` can block if runtime is no longer watching the channel, potential quiet leak.

## Why is it important?

Fixes the tamper protected Endpoint removal from the policy. 
This needs to go into 8.10 release.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Related issues

- Closes [ [Windows]: Agent with debug logs set gets unhealthy on removing Elastic Defend when Agent tamper protection is enabled ](https://github.com/elastic/elastic-agent/issues/3233)

@blakerouse @cmacknz I would appreciate your review or questions.

### CODE REVIEW

**Comment by aleksmaus** [comment]
All tamper protection related E2E tests passed. 
Some unrelated tests failed:
Screenshot 2023-08-24 at 6 37 51 PM

**Comment by cmacknz** [comment]
@Mergifyio update

**Review by cmacknz — APPROVED** [review]
Merging this, the problem it fixes shows up in tests outside of this PR somewhat regularly.

**Comment by aleksmaus** [comment]
> Merging this, the problem it fixes shows up in tests outside of this PR somewhat regularly.

IMHO, ideally the Agent runtime manager should probably be made more resilient sometime in the future, and do not block everything while waiting for the stopping component, and still possibly processing the "watch" channel updates if component sends few more status updates than expected. Thoughts?

**Comment by cmacknz** [comment]
Yes we have had bugs similar to this in the past, definitely a pattern. @faec has an in progress PR cleaning up some of the runtime manager, not sure if it would touch on this problem specifically though.

**Pull request merged**
