### PR TITLE
[Upgrade Details] Use `details.DownloadRate` type from elastic-agent-libs

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This is a refactoring PR. It moves the `details.DownloadRate` type from the `github.com/elastic/elastic-agent` module to the `github.com/elastic/elastic-agent-libs` module.

## Why is it important?

So packages within the `github.com/elastic/elastic-agent-libs` module can reuse the `details.DownloadRate` type; see https://github.com/elastic/elastic-agent-libs/pull/166.

## Related issues
* Closes https://github.com/elastic/elastic-agent/issues/3792

### CODE REVIEW

**Review by belimawr — APPROVED** [review]

**Review by blakerouse — APPROVED** [review]
Looks good.

Lint issue is bogus, I have seen it complain before when no gomod replace is present in the PR.

**Comment by cmacknz** [comment]
I'm fine to force merge this if we are certain the integration tests hanging is not unique to this PR. I haven't had a chance to look at that yet.

**Comment by cmacknz** [comment]
Let's force merge to at least get us past the test failures on main, it looks like at least one previous run completed and hit another known issue.

**Comment by belimawr** [comment]
Thanks a lot Craig! I ran the whole test suit at least two times in a row yesterday from my machine and the tests always passed.

**Pull request merged**
