### PR TITLE
Revert "add a DEB integration test"

### PR DESCRIPTION
**Pull request by rdner**
Reverts elastic/elastic-agent#4301

The Serverless Beats Tests step in our daily builds started failing with:

> Error: error running test: missing required Elastic Agent package builds for integration runner to execute: /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-linux-x86_64.tar.gz, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-linux-x86_64.tar.gz.sha512, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-x86_64.rpm, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-x86_64.rpm.sha512, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-amd64.deb, /tmp/beats-build/beats/x-pack/metricbeat/build/distributions/elastic-agent-8.14.0-SNAPSHOT-amd64.deb.sha512
~/builds/bk-agent-prod-gcp-1710406561496364062/elastic/elastic-agent

The last successful build is https://buildkite.com/elastic/elastic-agent/builds/7707
The first failure is https://buildkite.com/elastic/elastic-agent/builds/7735

There were only 2 changes made between these, this change is one of them. Let's try to revert this first because it has the least impact.

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by leehinman** [comment]
Fix is easy.  Line 23 in `.buildkit/scripts/steps/beats_tests.sh` should be:

```
    SNAPSHOT=true PLATFORMS=linux/amd64 PACKAGES=tar.gz,zip,deb,rpm mage package
```

it adds the deb & rpm packages.

My question is why did we pass all the tests when #4301 was merged?

**Comment by rdner** [comment]
The next daily build passed https://buildkite.com/elastic/elastic-agent/builds/7791
This confirms that the change was the cause of the failure.

**Comment by rdner** [comment]
@leehinman we run serverless tests only on daily builds, therefore it was not caught before.

**Comment by leehinman** [comment]
> @leehinman we run serverless tests only on daily builds, therefore it was not caught before.

Well I opened up #4424 to restore this, with the potential fix.  But given that the serverless tests won't run, do we just merge and hope for the best?  @pierrehilbert @jlind23 this seems like a gap we will want to close in the near future.

**Comment by cmacknz** [comment]
You could also just run the script the beats tests use to check that you can past the broken step manually:

https://github.com/elastic/elastic-agent/blob/a7034ef9c4a1eea4b8caaf983c7ed2f2c18468e9/.buildkite/scripts/steps/beats_tests.sh#L14-L36

**Pull request merged**
