### PR TITLE
[Tests] Update K8s and Kind version

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?

Update K8s and Kind version being used in testing to support 1.27 K8s version.

## Related issues

Relates to https://github.com/elastic/observability-dev/issues/2531.

### CODE REVIEW

**Review by MichaelKatsoulis — APPROVED** [review]

**Review by cmacknz — APPROVED** [review]

**Comment by AndersonQ** [comment]
I opened an issue for the flaky test and a PR to skip it:
 - https://github.com/elastic/elastic-agent/issues/3221
 - https://github.com/elastic/elastic-agent/pull/3222

**Comment by AndersonQ** [comment]
if you rebase onto main, you'll get https://github.com/elastic/elastic-agent/pull/3222, which should fix the flaky test

**Comment by constanca-m** [comment]
Thanks @AndersonQ :)

**Comment by constanca-m** [comment]
@AndersonQ Do you have any idea why it is failing now? It seems once again unrelated to this PR

**Comment by AndersonQ** [comment]
I'm checking

**Comment by AndersonQ** [comment]
there is a race condition, I'm working on a fix already

**Comment by AndersonQ** [comment]
I opened a PR: https://github.com/elastic/elastic-agent/pull/3243

I haven't seen this error before, it might be we were luck this time it happened. So perhaps rerunning your tests won't trigger it. As it's unrelated to your changes, if the tests pass before my PR is merged, I don't see any problem merging this one

**Comment by constanca-m** [comment]
I am out of luck @AndersonQ , now the tests are failing for something related to windows again, also unrelated to this changes. I don't have permissions to merge this PR, could you do it?

**Comment by constanca-m** [comment]
Hey @AndersonQ, what about the test that is failing for this PR? Could you merge it?

**Comment by AndersonQ** [comment]
@constanca-m could you rebase it onto `main`? With https://github.com/elastic/elastic-agent/pull/3249 merged, it should pass the tests now

**Comment by constanca-m** [comment]
Unfortunately, it still doesn't work @AndersonQ

**Review by AndersonQ — APPROVED** [review]

**Pull request merged**
