### PR TITLE
added cloudbeat to packages.yml

### PR DESCRIPTION
**Pull request by DaveSys911**
## What does this PR do?
Adds cloudbeat as bundled in beat.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by michalpristas — APPROVED** [review]
this looks allright, other changes like spec file seems in place

**Review by aleksmaus — APPROVED** [review]

**Comment by ph** [comment]
@mergify.io queue

**Comment by ph** [comment]
@mergifyio queue

**Comment by ph** [comment]
https://github.com/Mergifyio requeue

**Pull request merged**
