### PR TITLE
redact secret_paths from elastic-agent inspect output

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

redact secret_paths from elastic-agent inspect output.
`elastic-agent inspect` will now redact the value for any key in the `secret_paths` array.
`secret_paths` is expected to be part of the policy.

## Why is it important?

displaying secrets is to be avoided

## Checklist

- [x] My code follows the style guidelines of this project
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

Output of `elastic-agent inspect` will change. Any workflow that uses this command to extract  secret values will be broken.

### CODE REVIEW

**Comment by ycombinator** [comment]
@lucabelluccini Heads up on the [disruptive user impact](https://github.com/elastic/elastic-agent/pull/5621#issue-2553310950) due to this change

**Review by blakerouse — APPROVED** [review]
Looks good and has good test coverage.

**Comment by rowlandgeoff** [comment]
Rerunning the failed Sonar steps in the PR got this unblocked

**Comment by michel-laterman** [comment]
Looks like an integration test is failing:
```
>>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): container_cmd_test.go:261:
--
  | >>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): Error Trace:	/home/ubuntu/agent/testing/integration/container_cmd_test.go:261
  | >>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): Error:      	Condition never satisfied
  | >>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): Test:       	TestContainerCMDWithAVeryLongStatePath/small_path
  | >>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): Messages:   	Elastic-Agent did not report healthy. Agent status error: "<nil>", Agent logs
  | >>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): agent container initialisation - chown paths
  | >>> (linux-amd64-ubuntu-2404-container) Test output (sudo) (stdout): Warning: failed to walk path /tmp/foo/bar: lstat /tmp/foo/bar: no such file or directory
```

**Pull request merged**
