### PR TITLE
Add mage notice target

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Adds ```mage notice``` target

## Why is it important?

Convenient for magicians

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Screenshots

Screenshot 2023-11-15 at 12 24 47 PM

### CODE REVIEW

**Review by AndersonQ — APPROVED** [review]

**Comment by aleksmaus** [comment]
buildkite test this

**Comment by aleksmaus** [comment]
the integrations tests failure is unrelated to this change, can be merged any time

**Review by pchila — APPROVED** [review]

**Comment by pchila** [comment]
buildkite test this

**Comment by aleksmaus** [comment]
@AndersonQ if you have force merge permissions feels free to merge this PR. CI keeps failing on unrelated to this PR issue.

**Comment by AndersonQ** [comment]
@aleksmaus I do not have. You can try updating it with main or asking @cmacknz to force merge it

**Pull request merged**
