### PR TITLE
DEBUG PR - DO NOT MERGE - Investigate arm64 failures

### PR DESCRIPTION
**Pull request by pchila**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
The most recent test run caught it. There is a rollback in `TestStandaloneDowngradeToSpecificSnapshotBuild`

The watcher removes both agents, but we have the logs of what happened in the zip of the installation directory outside the data directory. The last log file is the watcher log:

```json
{"log.level":"info","@timestamp":"2024-02-07T22:45:55.401Z","log.origin":{"file.name":"cmd/watch.go","file.line":67},"message":"Upgrade Watcher started","process.pid":24780,"agent.version":"8.13.0","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:45:55.406Z","log.origin":{"file.name":"upgrade/watcher.go","file.line":66},"message":"Agent watcher started","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:10.407Z","log.origin":{"file.name":"upgrade/watcher.go","file.line":133},"message":"Trying to connect to agent","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:10.408Z","log.origin":{"file.name":"upgrade/watcher.go","file.line":164},"message":"Connected to agent","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:10.411Z","log.origin":{"file.name":"upgrade/watcher.go","file.line":197},"message":"Communicating with PID 24739","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:54.901Z","log.origin":{"file.name":"cmd/watch.go","file.line":176},"message":"Grace period passed, not watching","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-02-07T22:46:54.901Z","log.origin":{"file.name":"upgrade/watcher.go","file.line":184},"message":"Lost connection: failed reading next state: rpc error: code = Canceled desc = context canceled","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:54.906Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":59},"message":"Cleaning up upgrade","hash":"8dcab2","remove_marker":true,"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:56.907Z","log.origin":{"file.name":"upgrade/step_mark.go","file.line":156},"message":"Removing marker file","file.path":"/opt/Elastic/Agent/data/.update-marker","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:56.907Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":82},"message":"Removing previous symlink path","file.path":"/opt/Elastic/Agent/elastic-agent.prev","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:56.907Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":97},"message":"Removing hashed data directory","file.path":"/opt/Elastic/Agent/data/elastic-agent-8.13.0-SNAPSHOT-b04c7c","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-07T22:46:57.198Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":97},"message":"Removing hashed data directory","file.path":"/opt/Elastic/Agent/data/elastic-agent-8.13.0-SNAPSHOT-8dcab2","ecs.version":"1.6.0"}
```

1. We shouldn't be rolling back.
2. When we rollback we should only remove one directory, not both.

**Comment by pchila** [comment]
@cmacknz Agreed, it seems that `TestStandaloneDowngradeToSpecificSnapshotBuild` also according to the assertions I added at the beginning and end of an install test: https://buildkite.com/elastic/elastic-agent/builds/6911#018d8596-1f53-44e7-93ef-857bc1b4ff31
```
 fixture_install.go:250: 
        	Error Trace:	/home/ubuntu/agent/pkg/testing/fixture_install.go:250
        	            				/home/ubuntu/agent/pkg/testing/fixture_install.go:171
        	            				/usr/local/go/src/testing/testing.go:1169
        	            				/usr/local/go/src/testing/testing.go:1347
        	            				/usr/local/go/src/testing/testing.go:1589
        	Error:      	Should be empty, but was map[24739:{elastic-agent sleeping elastic-agent {true 24739} {true 1} {true 24739} {true 8} [elastic-agent] elastic-agent /opt/Elastic/Agent /opt/Elastic/Agent/data/elastic-agent-8.13.0-SNAPSHOT-8dcab2/elastic-agent (deleted) {} {{true 1866608640} {true 44302336} {{true 64299008} {false 0}}} {2024-02-07T22:43:49.000Z {{true 113120} {true 113120} {false 0} {{false 0}}} {{true 109050}} {{true 4070}}} {{true 13} {{true 524288} {true 524288}}}  {{true 2863279039} {true 2960920929} {true 498182} {true 71961} {true 16384} {true 2968231936} {true 0}}  2024-02-07 22:47:05.186490518 +0000 UTC m=+1472.857833919}]
        	Test:       	TestStandaloneDowngradeToSpecificSnapshotBuild
        	Messages:   	there should be no running agent at the end of the test
```

There is no error at the beginning of the test (this means there were no agents running when we started) but we have a leftover agent process after uninstall (which is skipped btw) and that is shown with the same PID in all the other failed tests on the same runner, for example in `TestStandaloneUpgradeWithGPGFallback`

```
    fixture_install.go:250: 
        	Error Trace:	/home/ubuntu/agent/pkg/testing/fixture_install.go:250
        	            				/home/ubuntu/agent/pkg/testing/fixture_install.go:130
        	            				/home/ubuntu/agent/testing/upgradetest/upgrader.go:255
        	            				/home/ubuntu/agent/testing/integration/upgrade_gpg_test.go:81
        	Error:      	Should be empty, but was map[24739:{elastic-agent sleeping elastic-agent {true 24739} {true 1} {true 24739} {true 8} [elastic-agent] elastic-agent /opt/Elastic/Agent /opt/Elastic/Agent/data/elastic-agent-8.13.0-SNAPSHOT-8dcab2/elastic-agent (deleted) {} {{true 1866608640} {true 44302336} {{true 64299008} {false 0}}} {2024-02-07T22:43:49.000Z {{true 113130} {true 113130} {false 0} {{false 0}}} {{true 109060}} {{true 4070}}} {{true 13} {{true 524288} {true 524288}}}  {{true 2863279039} {true 2960920929} {true 498182} {true 71961} {true 16384} {true 2968231936} {true 0}}  2024-02-07 22:47:46.59348687 +0000 UTC m=+1514.264830276}]
        	Test:       	TestStandaloneUpgradeWithGPGFallback
        	Messages:   	there should be no running agent at beginning of Install()
```

I am going to temporarily skip the test while we figure out how to fix it

**Comment by cmacknz** [comment]
> I am going to temporarily skip the test while we figure out how to fix it

What this bug is, is bricking the agent by uninstalling it. This is in the category of "we cannot release the agent at all" until we know what is causing it.

**Comment by pchila** [comment]
> > I am going to temporarily skip the test while we figure out how to fix it
> 
> Whatever this bug is, is bricking the agent by uninstalling it. This is in the category of "we cannot release the agent at all" until we know what is causing it.

A normal user would not obsessively install/uninstall elastic-agent repeatedly with short interval in between.

The removal of all the agent installs comes from the fact that our watcher (by design, confirmed this with @michalpristas  during development of the "agent version in path" feature) remove *every* agent installation it finds under `/opt/Elastic/Agent/data` except the previous one (in case of rollback) or the current one (in case of successful upgrade).

If a watcher is left lingering from another test, it will remove any agent installs except the one that was supposed to survive in the test it was spawned in: if none of the currently installed agent hash the same version/hash it will remove everything.

We have confirmation that there are some `elastic-agent` processes still running before install or after uninstall for different tests thanks to the asserts I have added, now I am trying to understand where those processes are coming from and why they keep running beyond the scope of the test they have been launched in.

**Pull request closed without merging**
