### PR TITLE
change syncExpected to use proto.Equal

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?

Another half of https://github.com/elastic/elastic-agent/issues/1738

This changes the `syncExpected()` method used by the unit state manager to use `proto.Equal()` instead of `reflect.DeepEqual()`.

Still haven't tested this, as I'm running into some issues with `mage package` not generating all the build artifacts.

## Why is it important?

This will hopefully fix the issue with elastic-agent generating erroneous updated units.

### CODE REVIEW

**Comment by cmacknz** [comment]
Let's bump the agent client version here as well: https://github.com/elastic/elastic-agent/blob/67021cfc1b66136e42a1570c559f5da4f11f68fe/go.mod#L16

**Review by cmacknz — APPROVED** [review]

**Comment by fearful-symmetry** [comment]
It appears that `make notice` is producing different results locally and in CI. So, working on that....

**Comment by cmacknz** [comment]
Running `make notice` or `make check-ci` locally for me produces no changes.

**Comment by fearful-symmetry** [comment]
Okay, so CI seems to be reverting the changes made specifically by `go mod tidy`. Not sure why yet.

**Comment by cmacknz** [comment]
The elastic-agent-client repository had an invalid commit in it's go.mod, bumping the client version again to include https://github.com/elastic/elastic-agent-client/pull/48 will likely fix the notice/mod file problems.

**Comment by cmacknz** [comment]
Merged, want to make sure we get this in the next BC.

**Pull request merged**
