### PR TITLE
Fix container paths config

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR fixes the parsing of paths from the `container-paths.yml` file used internally when `elastic-agent container` is run.

## Why is it important?

So the expected paths are loaded from `container-paths.yml`.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Looks good!

**Comment by cmacknz** [comment]
Is there an issue we can link this to? I assume this is a follow up from https://github.com/elastic/elastic-agent/pull/2330 for https://github.com/elastic/elastic-agent/issues/2315?

I want to make sure we know what bug this is fixing so we can make sure it gets tested properly. If it's linked to https://github.com/elastic/elastic-agent/issues/2315 then the test is that Heartbeat is able to start under the conditions described in that issue.

**Comment by ycombinator** [comment]
> Is there an issue we can link this to? I assume this is a follow up from #2330 for #2315?
> 
> I want to make sure we know what bug this is fixing so we can make sure it gets tested properly. If it's linked to #2315 then the test is that Heartbeat is able to start under the conditions described in that issue.

There's no issue per se that this fixes.  I noticed the incorrect struct tags as part of investigating https://github.com/elastic/elastic-agent/issues/2315.  But the actual fix for https://github.com/elastic/elastic-agent/issues/2315 is #2330.

**Comment by cmacknz** [comment]
Thanks, no opposition to the change I just want to understand any intended (or unintended) consequences.

**Comment by ycombinator** [comment]
> I just want to understand any intended (or unintended) consequences.

Thanks for calling this out.  I did some testing as well as digging into the PR that introduced the `/usr/share/elastic-agent/container-paths.yml` file: https://github.com/elastic/beats/pull/25204.  

From reading that PR and the issue it fixed (https://github.com/elastic/beats/issues/24956), I understand why the file is used for persisting the state path - so that commands like `elastic-agent status` can "find" the state directory (and the `elastic-agent-control.sock` socket file thereafter).  However, I haven't been able to figure why other paths, i.e. the logs path and the config path, are also being persisted in the `/usr/share/elastic-agent/container-paths.yml` file.  

Put another way, after I started up an Elastic Agent container and deleted the `/usr/share/elastic-agent/container-paths.yml` file, running `elastic-agent status` inside that container did not work, as expected, because the state path is no longer persisted.  But what else should be breaking because the logs path and config path are no longer persisted either?  I think answering this question would help figure out the consequences of the changes in this PR here.  

@blakerouse Can you help answer the above question?

**Comment by blakerouse** [comment]
@ycombinator I provided some input over Slack, but didn't add it to this PR.

I took another look at this and I believe that the `config_path` and `log_path` are still important and required.

The `config_path` is needed by the `inspect` command, otherwise it will not find the configuration. The `log_path` is needed for the `diagnostics` command or it would not be able to gather the logs for the diagnostics bundle.

**Comment by ycombinator** [comment]
Thanks @blakerouse.  I started to test this PR by comparing the outputs of `elastic-agent status`, `elastic-agent inspect`, and `elastic-agent diagnostics` (specifically the `logs` folder in the bundle) from this PR's build with a build from `main`.  Unfortunately, while doing this, I found a bug: https://github.com/elastic/elastic-agent/issues/2470.   So I have to wait until that bug is resolved before resuming testing on this PR.

**Comment by pierrehilbert** [comment]
@ycombinator do we need another round of review here?

**Comment by ycombinator** [comment]
> @ycombinator do we need another round of review here?

@pierrehilbert Not yet.  It's on my plate to test the changes in this PR; I just haven't gotten around to it yet.

**Comment by ycombinator** [comment]
> I started to test this PR by comparing the outputs of `elastic-agent status`, `elastic-agent inspect`, and `elastic-agent diagnostics` (specifically the `logs` folder in the bundle) from this PR's build with a build from `main`. 

I got around to testing this PR again, as described above.  I see no differences when running the three commands using a build from this PR vs. using a build from `main`.  

I also tested running the Agent as a Docker container, pausing/unpausing it and stopping/starting it.  I did this with the build from the PR as well as the build from `main` and, again, I see no differences in behavior.

So I don't believe this PR will introduce any intended or unintended consequences.

**Pull request merged**
