### PR TITLE
Move mage targets to libraries so the shipper can use them

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?

This moves a handful of functions and mage targets in the main `magefile.go` to helper libs in `dev-tools` so we can import them into the shipper.

This also fixes the `notice` target, which literally refused to run locally for me.

## Why is it important?

We need some of these targets in the shipper. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
Ahh, looks like the main magefile hasn't been touched by the linter before. This'll take a few minutes...

**Comment by cmacknz** [comment]
This will close https://github.com/elastic/elastic-agent/issues/321

**Comment by cmacknz** [comment]
I started trying to generate a NOTICE file for the shipper repo yesterday: https://github.com/elastic/elastic-agent-shipper/pull/20

I ran into the same issue with the notice target here being broken (initially I just copied it to the shipper). Probably the file is out of date in the agent repo.

Once this is merged I'll update my PR above with these targets

**Comment by fearful-symmetry** [comment]
So while I wasn't looking, @kvch merged  https://github.com/elastic/elastic-agent-system-metrics/pull/10 and  https://github.com/elastic/elastic-agent-libs/pull/39, which means I'm closing this for now. If we want to re-open this for the sake of cleanup, we can, but until then, I can move onto other things.

**Pull request closed without merging**
