### PR TITLE
Change to local artificats source uri.

### PR DESCRIPTION
**Pull request by sqrtZeroKnowledge**
## What does this PR do?
Generally it back with failure of not founding an online binary artifacts from elastic.co.

## Why is it important?
Usually there is many users who use Elastic Security Air-gapped and better to provide a local artifacts.

- [ ] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by michalpristas** [comment]
seems like a wrong merge. 8.4 to main

**Comment by sqrtZeroKnowledge** [comment]
Yeah its my bad thats tested on 8.4

**Comment by michalpristas** [comment]
inactivity

**Comment by AndersonQ** [comment]
@sqrtZeroKnowledge dos you still consider this PR relevant? If so, could you please rebase it, fix the conflicts and better explain what it does?

If not, you can close it, or we'll do it soon

**Pull request closed without merging**
