### PR TITLE
Omit download rate when it is calculated as +Inf to prevent checkin errors

### PR DESCRIPTION
**Pull request by cmacknz**
- Closes https://github.com/elastic/elastic-agent/issues/4041

We can calculate download rates of +Inf if the download happens quickly enough, which when sent as part of the checkin payload causes the checkin to fail because only finite float values can be indexed in ES.

Since +Inf isn't informative to the user, just omit it since `download_rate` is optional. Do the same for -Inf and NaN in case those values ever happen.

### CODE REVIEW

**Comment by cmacknz** [comment]
buildkite test it

**Comment by ycombinator** [comment]
With the changes in this PR, I wonder if we even need the [`details.DownloadRate` type](https://github.com/elastic/elastic-agent-libs/blob/1cf0afdc6c934ab507ef043e7d920435419af61d/upgrade/details/details.go#L31) any more?

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
> With the changes in this PR, I wonder if we even need the [details.DownloadRate type](https://github.com/elastic/elastic-agent-libs/blob/1cf0afdc6c934ab507ef043e7d920435419af61d/upgrade/details/details.go#L31) any more?

Hmm, didn't notice we had that. We don't need the +Inf handling, we want to keep the edit to the precision in the string.

**Review by ycombinator — APPROVED** [review]
LGTM.

**Comment by cmacknz** [comment]
```
=== RUN   TestFQDN
    fqdn_test.go:49: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/fqdn_test.go:49
        	Error:      	Received unexpected error:
        	            	Get "https://api.ipify.org": net/http: TLS handshake timeout
        	Test:       	TestFQDN
--- FAIL: TestFQDN (23.09s)
```

Failure unrelated, will open an issue for this. Force merging.

**Pull request merged**
