### PR TITLE
Update CODEOWNERS for Eng Prod ownership

### PR DESCRIPTION
**Pull request by rowlandgeoff**
Update CODEOWNERS so the Eng Prod team is automatically added to reviews where CI is getting updated.

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Review by jlind23 — APPROVED** [review]

**Comment by rowlandgeoff** [comment]
Note to self: the `skip-ci` label doesn't seem to work:
image

**Review by swiatekm — APPROVED** [review]

**Comment by rowlandgeoff** [comment]
buildkite test this

**Comment by rowlandgeoff** [comment]
CI isn't triggering now, it may be an effect of having tried the `skip-ci` label. Considering this change safe and merging.

**Pull request merged**
