### PR TITLE
Fixing helm-chart values.yaml presets docs

### PR DESCRIPTION
**Pull request by SampaioLeal**
## What does this PR do?

This PR fixes the presets terms used in comment-docs of the elastic-agent helm-chart values.yaml

## Why is it important?

Keep docs consistent to avoid headaches

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

### CODE REVIEW

**Review by pkoutsovasilis — COMMENTED** [review]
Hi @SampaioLeal 👋 thank you for fixing these typos. could you please also update them in deploy/helm/elastic-agent/README.md

**Comment by SampaioLeal** [comment]
> Hi @SampaioLeal 👋 thank you for fixing these typos. could you please also update them in deploy/helm/elastic-agent/README.md
> 
> PS: you will also have to sign the CLA 🙂 

I saw the CLA after the pr 😆 
Ok, I'll take a look at the readme

**Review by swiatekm — APPROVED** [review]

**Review by swiatekm — COMMENTED** [review]
I'd be fine merging this as-is, but @pkoutsovasilis request is valid, so I'll retract my approval for now.

**Comment by swiatekm** [comment]
On a related note, do we have a spell checker running over these docs?

**Comment by ycombinator** [comment]
> On a related note, do we have a spell checker running over these docs?

I don't believe so.  It's a good idea.  I created a private issue to track adding one across multiple repositories and tagged you in it.  Feel free to add any suggestions there.

**Review by pkoutsovasilis — APPROVED** [review]

**Review by swiatekm — APPROVED** [review]

**Review by mauri870 — APPROVED** [review]

**Comment by mauri870** [comment]
Thanks!

**Comment by ycombinator** [comment]
buildkite test this

**Review by blakerouse — APPROVED** [review]

**Comment by ycombinator** [comment]
Thanks for your contribution, @SampaioLeal!

**Pull request merged**
