### PR TITLE
Increate BK Agent Resources for Ind Agent Step

### PR DESCRIPTION
**Pull request by dwhyrock**
## What does this PR do?
This PR increases the CPU and disk size resources for the `bk-api-publish-independent-agent` step in the `elastic-agent-pipeline`.  

## Why is it important?
The `bk-api-publish-independent-agent` step was more-often-than-not getting killed in Buildkite due to using too many resources for the size of the k8s agent.  By increasing the CPU and disk size, this does not happen anymore.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by gogochan — APPROVED** [review]

**Review by cmacknz — APPROVED** [review]

**Review by pchila — APPROVED** [review]

**Comment by dwhyrock** [comment]
The Integration tests have failed twice.  I added another empty commit to re-run them again.

I'm seeing this error:
```
>>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): === FAIL: testing/integration TestStandaloneUpgradeRollbackOnRestarts (0.04s)
>>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): upgrade_rollback_test.go:178:
>>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_rollback_test.go:178
>>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): Error:      	Received unexpected error:
>>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): failed to prepare before exec: failed to find snapshot URI for version 8.13.2: failed to find package URL: Get "https://artifacts-api.elastic.co/v1/search/8.13.2/elastic-agent": tls: failed to verify certificate: x509: certificate is valid for ingress.local, not artifacts-api.elastic.co
```

Link: https://elastic.slack.com/archives/C06CU8J2C5N/p1712975331796469

Unsure if this is a transient issue, or if something else is amiss.  Appreciate any feedback.

**Comment by pchila** [comment]
> The Integration tests have failed twice. I added another empty commit to re-run them again.
> 
> I'm seeing this error:
> 
> ```
> >>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): === FAIL: testing/integration TestStandaloneUpgradeRollbackOnRestarts (0.04s)
> >>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): upgrade_rollback_test.go:178:
> >>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_rollback_test.go:178
> >>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): Error:      	Received unexpected error:
> >>> (linux-amd64-ubuntu-2204-upgrade) Test output (sudo) (stdout): failed to prepare before exec: failed to find snapshot URI for version 8.13.2: failed to find package URL: Get "https://artifacts-api.elastic.co/v1/search/8.13.2/elastic-agent": tls: failed to verify certificate: x509: certificate is valid for ingress.local, not artifacts-api.elastic.co
> ```
> 
> Link: https://elastic.slack.com/archives/C06CU8J2C5N/p1712975331796469
> 
> Unsure if this is a transient issue, or if something else is amiss. Appreciate any feedback.

It looks like we failed to download elastic-agent 8.14.0-SNAPSHOT when upgrading from 7.17.20...
```
Error: Failed trigger upgrade of daemon: initiating fetcher: failed to detect remote snapshot repo, proceeding with configured: Get "https://artifacts-api.elastic.co/v1/search/8.14.0-SNAPSHOT/elastic-agent": dial tcp 35.188.12.98:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
These are normally transient (albeit annoying) errors, I will restart the integration test step...

**Comment by dwhyrock** [comment]
> These are normally transient (albeit annoying) errors, I will restart the integration test step...

Thanks.  However, it looks like that one failed as well.  https://buildkite.com/elastic/elastic-agent/builds/8361#018ee606-fb10-41a2-a1ce-9b20f4a242d7/598-1023

Last error message (with a bunch of other `failed` messages above it)
```
Error: error running test: failed to check for cloud 8.14.0-SNAPSHOT [stack_id: 8140-SNAPSHOT, deployment_id: dd6a85223ca14ec6aec7485a85f62a96] to be ready: context deadline exceeded
```

I've pushed another empty commit to retry the testing for a 5th time.

**Comment by dwhyrock** [comment]
Similar error again as the last message.

Plus, now the Extended runtime leak tests failed as well: https://buildkite.com/elastic/elastic-agent/builds/8367#018ee6b0-0640-4ff2-9311-2c02b6a3bfd7/598-674
```
>>> (windows-amd64-2022-fleet) Failed for instance windows-amd64-2022-fleet (@ 34.66.183.199): failed to check for cloud 8.14.0-SNAPSHOT [stack_id: 8140-SNAPSHOT, deployment_id: 8ac9d66e04944717a1c2fcd65f8cf617] to be ready: context deadline exceeded
>>> (linux-amd64-ubuntu-2204-fleet) Failed for instance linux-amd64-ubuntu-2204-fleet (@ 35.202.65.238): failed to check for cloud 8.14.0-SNAPSHOT [stack_id: 8140-SNAPSHOT, deployment_id: 8ac9d66e04944717a1c2fcd65f8cf617] to be ready: context deadline exceeded
>>> (linux-arm64-ubuntu-2204-fleet) Failed for instance linux-arm64-ubuntu-2204-fleet (@ 34.31.204.135): failed to check for cloud 8.14.0-SNAPSHOT [stack_id: 8140-SNAPSHOT, deployment_id: 8ac9d66e04944717a1c2fcd65f8cf617] to be ready: context deadline exceeded
Error: error running test: failed to check for cloud 8.14.0-SNAPSHOT [stack_id: 8140-SNAPSHOT, deployment_id: 8ac9d66e04944717a1c2fcd65f8cf617] to be ready: context deadline exceeded
~/builds/bk-agent-prod-gcp-1713267283132963345/elastic/elastic-agent
Cannot generate HTML test report: build/TEST-go-integration.xml not found
```

Looks like I'm getting very unlucky in the flakiness department here, lol.

Pushing another empty commit to do testing yet again.

**Comment by pierrehilbert** [comment]
I think this is related to the ongoing issue on Elastic Cloud deployment we have.
Craig rollbacked the change which introduced that issue and we will have to wait for a new build to get things fixed.

**Pull request merged**
