### PR TITLE
Lower retry count and improve error message of uninstall notifications

### LINKED ISSUE #5752: elastic-agent installed as Fleet server remains stuck in uninstalling with retry errors for over 4-5 minutes.
**Kibana Build details:**
```
VERSION: 8.16.0 SNAPSHOT
BUILD: 78993
COMMIT: 6eb8471c3124046eca03cccf20e0cc4f9706bcd5
```
Artifact: https://snapshots.elastic.co/8.16.0-106cdbc2/downloads/beats/elastic-agent/elastic-agent-8.16.0-SNAPSHOT-windows-x86_64.zip

Host: Windows Server 2022- Test Signing ON

**Preconditions:**
1. 8.16.0 SNAPSHOT Kibana self-managed environment should be available.
2. Agent should be installed using Quickstart or Production mode of security.

**Steps to reproduce:**
1. Observe Fleet Server is installed.
2. Run `.\Elastic\Agent\elastic-agent.exe uninstall`.
3. Observe notify: Fleet network error[retry] error is stuck for more than 4 minutes.
4. Observe folder is already blank before the completion.

**Expected Result:**
elastic-agent installed as Fleet server should not remain stuck in  uninstalling with retry errors for over 4-5 minutes.

**Screenshots:**
Image
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Lower the retry count and fix progress error messages for the unreleased uninstall notification features.

## Why is it important?

With the current retry count the agent may be stuck for a few minutes while uninstalling

## Checklist

- ~~My code follows the style guidelines of this project~~
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- ~~I have added tests that prove my fix is effective or that my feature works~~
- ~~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~I have added an integration test or an E2E test~~

## Related issues

- Closes #5752

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]

**Comment by cmacknz** [comment]
We need to permanently log (i.e. not just as a transient message) why we are contact Fleet Server, not just that we are doing it, so that users can understand why they are waiting.

We should also consider having a configuration option to bypass this notification. There is a near trivial bypass for those with patience regardless, which is turning of the local network connection. 

Currently we are most likely just annoying users whose Fleet might unreachable for known reasons. Anyone who wants to bypass the audit trail of the uninstall notification can just disable the network already.

**Comment by michel-laterman** [comment]
I've created an issue to track skipping the notification entirely: https://github.com/elastic/elastic-agent/issues/5757.

**Comment by michel-laterman** [comment]
buildkite test this

**Comment by jlind23** [comment]
buildkite test this

**Review by swiatekm — APPROVED** [review]

**Pull request merged**
