### PR TITLE
Improve sync handling and errors

### PR DESCRIPTION
**Pull request by narph**
## What does this PR do?

Improve sync handling and errors

## Why is it important?

Improve sync handling and errors
Related to https://github.com/elastic/elastic-agent/issues/98

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

Will update https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L44 by adding `SyncParent` once it's available in the repo.

## Related issues

- Relates https://github.com/elastic/elastic-agent-libs/pull/36 https://github.com/elastic/elastic-agent/issues/98

### CODE REVIEW

**Review by ph — APPROVED** [review]
LGTM

**Comment by narph** [comment]
tests will fail until changes here https://github.com/elastic/elastic-agent-libs/pull/36 are in

**Comment by ph** [comment]
@blakerouse @narph @mtojek  Would like your opinion on this, should we backport this?

**Comment by mtojek** [comment]
From a flakiness perspective, we should go down to 7.16.

**Comment by jlind23** [comment]
@mtojek we do not backport anymore to 7.16  so not sure how to understand your comment.

**Comment by ph** [comment]
I think @mtojek meant 7.17, if the fix is successful we might want to  target it.

**Comment by mtojek** [comment]
Julien is right in this case, but it's fine if we do not do this. We may need a workaround or fix in our Integrations environment to prevent flakiness for unsupported stacks. Currently, we're testing against the oldest stack version, supported by the integration.

**Pull request merged**
