### PR TITLE
Run ITs on PRs

### PR DESCRIPTION
**Pull request by pazone**
- Enhancement
## What does this PR do?
Enables integration tests for pull requests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added an integration test or an E2E test

## How to test this PR locally
Make sure that integration tests are executed on pull requests to main branch

### CODE REVIEW

**Comment by pazone** [comment]
buildkite build this

**Comment by pazone** [comment]
buildkite build this

**Comment by faec** [comment]
buildkite build this

**Comment by pazone** [comment]
buildkite build this

**Comment by jlind23** [comment]
@pierrehilbert now that @ycombinator fixed the remaining flakiness on the E2E tests, can we make this land?

**Comment by pierrehilbert** [comment]
@pazone you mentioned on Thursday that everything is ready on your side, is it still the case?
If it is, could we please merge this one?

**Review by pierrehilbert — APPROVED** [review]

**Comment by pazone** [comment]
buildkite build this

**Pull request merged**
