### PR TITLE
TestUpgradeBrokenPackageVersion: Detect version bump and conditionally skip test

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?

This PR checks if there has been a version bump along with an elastic-agent version pinning to the previous version.
If that is the case, skip `TestUpgradeBrokenPackageVersion` since removing the `package.version` file as it's done in that test will mess up the paths elastic-agent uses.

## Why is it important?

To prevent build failures during version bumps

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

-

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]
Thanks @pchila !

**Review by blakerouse — APPROVED** [review]

**Comment by pchila** [comment]
Example of skipping the test because package version and default version are different: https://buildkite.com/elastic/elastic-agent-extended-testing/builds/1263#01909ca3-7329-49ff-b71e-009dd07d53fc

image


Remains to be tested on main once we remove the pinning to 8.15.0 but I guess we could (either/or):
- wait for the bump to be finished and rebase (the test should run at that point)
- merge now and go back to check once the agent version pinning is removed

Any preference?

**Comment by ycombinator** [comment]
> merge now and go back to check once the agent version pinning is removed
This is my preference as it would let us test the conditional logic in both directions:
- now, before pinning is removed => test should not run
- after pinning is removed => test should run

**Comment by cmacknz** [comment]
Why does this test fail during the version bump? The agent was built as 8.15.0, and we fallback to being 8.16.0, and this confuses the test or the agent somehow?

I'm not opposed to skipping it if that is all we can do but I want to understand if we can just fix the problem causing the failure so our test framework doesn't temporarily let potential problems onto main.

Are we still changing the agent package version to the previous minor? If that is the root of this, we can probably eliminate that. If I recall we needed this because we failed the Fleet Server version compatibility check, for stateful this was relaxed for fleet-server snapshot versions some time ago. https://github.com/elastic/fleet-server/pull/3039

**Comment by pchila** [comment]
> Why does this test fail during the version bump? The agent was built as 8.15.0, and we fallback to being 8.16.0, and this confuses the test or the agent somehow?
> 

The version of the agent is part of some of the agent paths, removing the package.version file after installing as an 8.15 agent and falling back to BEAT_VERSION screws up where the agent thinks it's installed.

> I'm not opposed to skipping it if that is all we can do but I want to understand if we can just fix the problem causing the failure so our test framework doesn't temporarily let potential problems onto main.
> 
> Are we still changing the agent package version to the previous minor? If that is the root of this, we can probably eliminate that. If I recall we needed this because we failed the Fleet Server version compatibility check, for stateful this was relaxed for fleet-server snapshot versions some time ago. [elastic/fleet-server#3039](https://github.com/elastic/fleet-server/pull/3039)

The initial reason for the pinning was Fleet not accepting an agent newer than itself, if we don't need that we can avoid pinning agent version to the previous version and that in turn would let this test run...

**Comment by cmacknz** [comment]
> The initial reason for the pinning was Fleet not accepting an agent newer than itself, if we don't need that we can avoid pinning agent version to the previous version and that in turn would let this test run...

Yes this restriction is already removed for ESS agents, and we can change Fleet to do the same for serverless. So I vote we remove the version pinning of agent.

**Comment by pchila** [comment]
PR is in standby as we see what happens when removing the agent version pinning directly in https://github.com/elastic/elastic-agent/pull/5119

**Comment by pchila** [comment]
Closed in favor of #5119 5119

**Pull request closed without merging**
