### PR TITLE
Revert "[Service Runtime] Add ability for service operations to be retried (#2889)"

### LINKED ISSUE #3077: Agent fails to uninstall endpoint successfully when handling the Unenroll action
The agent fails to uninstall endpoint when handling the unenroll action, which is sent when a user unenrolls the agent from Fleet without selecting the force unenroll option (which just revokes API keys). 

The uninstall path here is starts from processing the unenroll action which generates an empty agent policy such that all inputs are uninstalled:

https://github.com/elastic/elastic-agent/blob/123579115ad7a330779c2f9b5b9e719f98282dc4/internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go#L55-L57

When this happens the agent keeps running and the Endpoint service directory is left on disk (at /Library/Elastic/Endpoint on a Mac), and the agent logs show the `endpoint-security` command exiting and immediately failing with a context cancelled error:

```json
{"log.level":"info","@timestamp":"2023-07-13T19:09:26.085Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service.go","file.line":216},"message":"uninstall endpoint service","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-07-13T19:09:26.085Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":191},"message":"service command execution failed with error [failed starting the command: failed to start \"/opt/Elastic/Agent/data/elastic-agent-123579/components/endpoint-security\": context canceled], retrying (will be retry [1]) after [10.798795076s]","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-07-13T19:09:26.085Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":1187},"message":"Component state changed endpoint-default (HEALTHY->STOPPED): Stopped: endpoint service runtime","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-07-13T19:09:26.085Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":1187},"message":"Unit state changed endpoint-default-93ee0555-32e8-4cbd-971c-434c33f508ca (HEALTHY->STOPPED): Stopped: endpoint service runtime","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"STOPPED"},"unit":{"id":"endpoint-default-93ee0555-32e8-4cbd-971c-434c33f508ca","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-07-13T19:09:26.085Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":1187},"message":"Unit state changed endpoint-default (HEALTHY->STOPPED): Stopped: endpoint service runtime","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"STOPPED"},"unit":{"id":"endpoint-default","type":"output","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-07-13T19:09:28.165Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":194},"message":"Possible transient error during checkin with fleet-server, retrying","log":{"source":"elastic-agent"},"error":{"message":"fail to checkin to fleet-server: all hosts failed: 1 error occurred:\n\t* requester 0/1 to host https://localhost:8220/ errored: Post \"https://localhost:8220/api/fleet/agents/b22533af-c447-40d1-87aa-1ea8bddde11c/checkin?\": context canceled\n\n"},"request_duration_ns":518852690,"failed_checkins":1,"retry_after_ns":65634696157,"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-07-13T19:09:28.165Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":211},"message":"checkin retry loop was stopped","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-07-13T19:09:31.564Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":154},"message":"Fleet gateway stopped","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-07-13T19:09:36.886Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":191},"message":"service command execution failed with error [failed starting the command: failed to start \"/opt/Elastic/Agent/data/elastic-agent-123579/components/endpoint-security\": context canceled], retrying (will be retry [2]) after [19.296305451s]","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-07-13T19:09:56.184Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":191},"message":"service command execution failed with error [failed starting the command: failed to start \"/opt/Elastic/Agent/data/elastic-agent-123579/components/endpoint-security\": context canceled], retrying (will be retry [3]) after [23.559704045s]","ecs.version":"1.6.0"}
```

What I suspect is happening is that some part of the agent is assuming the uninstall still happens synchronously, but the command now executes in a goroutine:

https://github.com/elastic/elastic-agent/blob/123579115ad7a330779c2f9b5b9e719f98282dc4/pkg/component/runtime/service_command.go#L171-L184

It is highly likely this is the source of the problem in https://github.com/elastic/elastic-agent/issues/3033 as well.

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR reverts https://github.com/elastic/elastic-agent/pull/2889.

## Why is it important?

The changes introduced in #2889 introduced a critical bug: #3077.  While we have a fix for that particular bug (#3086), the fundamental nature of the change introduced in #2889 — changing previously synchronous code paths for service install and uninstall operations to asynchronous — has the potential for introducing other unforeseen bugs in these critical operations.

As mentioned in https://github.com/elastic/elastic-agent/pull/3086#issuecomment-1638648385, 

> We should probably step back and consider having blocking retries for all the service operations (as opposed to non-blocking retries, as implemented in https://github.com/elastic/elastic-agent/pull/2889). It would greatly simplify the implementation but also probably reduce the likelihood of introducing bugs due to the unforeseen effects of non-blocking/async code paths.

## How to test this PR locally

_The example commands below are for MacOS systems._

### Adding Elastic Defend integration should install Endpoint

1. Build Elastic Agent with this PR.
   ```
   $ DEV=true EXTERNAL=true SNAPSHOT=true PLATFORMS=darwin/arm64 PACKAGES=tar.gz mage package
   ```
2. Extract the built Agent artifact and replace Endpoint files with signed versions.  Get signed versions by downloading the most recently released Agent artifact.
   ```
   $ cd /tmp
   $ tar xzf ~/development/github/elastic-agent/build/distributions/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64.tar.gz
   $ tar xzf ~/Downloads/elastic-agent-8.8.2-darwin-aarch64.tar.gz
   $ cp elastic-agent-8.8.2-darwin-aarch64/data/elastic-agent-cdc5ba/components/endpoint-security* elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-2d1d32/components
   ```

2. Enroll the Elastic Agent in Fleet.
   ```
   $ cd elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64
   $ sudo ./elastic-agent install --url=https://XXXXXXXXX:443 --enrollment-token=XXXXXXXXXXXXX
   ```

1. Verify that Endpoint isn't already installed on the system.
   ```
   $ sudo ls -l /Library/Elastic/Endpoint
   ls: /Library/Elastic/Endpoint: No such file or directory
   ```
2. In the Fleet UI, edit the enrolled Agent's policy and add the Elastic Defend integration.
4. After a few seconds, verify that Endpoint is installed on the system.
   ```
   $ sudo ls -l /Library/Elastic
   total 0
   drwxr-x---@ 17 root  wheel  544 Jul 17 15:02 Agent
   drwxr-xr-x@  9 root  wheel  288 Jul 17 15:07 Endpoint
   ```
5. In the Fleet UI, verify that the Agent is healthy.

### Unenrolling Elastic Agent should uninstall Endpoint

1. Complete the steps for adding Elastic Defend Integration, which should install Endpoint.
2. In the Fleet UI, unenroll Agent (do NOT check the "Remove Agent immediately" checkbox).
3. Wait until Agent disappears from the Fleet UI.
4. Verify that Endpoint isn't installed on the system.
   ```
   $ sudo ls -l /Library/Elastic/Endpoint
   ls: /Library/Elastic/Endpoint: No such file or directory
   ```

### Removing Elastic Defend integration should uninstall Endpoint
1. Complete the steps for adding Elastic Defend Integration, which should install Endpoint.
2. In the Fleet UI, remove the Elastic Defend integration from the enrolled Agent's policy.
3. Verify that Endpoint isn't installed on the system.
   ```
   $ sudo ls -l /Library/Elastic/Endpoint
   ls: /Library/Elastic/Endpoint: No such file or directory
   ```

### Switching to policy without Elastic Defend integration should uninstall Endpoint
1. Complete the steps for adding Elastic Defend Integration, which should install Endpoint.
2. In the Fleet UI, create a new policy that does not include Elastic Defend.
3. In the Fleet UI, update the enrolled Agent's policy to the new policy.
4. Verify that Endpoint isn't installed on the system.
   ```
   $ sudo ls -l /Library/Elastic/Endpoint
   ls: /Library/Elastic/Endpoint: No such file or directory
   ```

### Uninstalling Agent should uninstall Endpoint
1. Complete the steps for adding Elastic Defend Integration, which should install Endpoint.
2. From the command-line, uninstall Agent.
3. Verify that Endpoint isn't installed on the system.
   ```
   $ sudo ls -l /Library/Elastic/Endpoint
   ls: /Library/Elastic/Endpoint: No such file or directory
   ```

## Related issues

- Fixes #3077

### CODE REVIEW

**Review by aleksmaus — APPROVED** [review]
LGTM. less is more. thanks!

**Comment by kevinlog** [comment]
We should be sure to test the following after this revert PR goes in.

- unenrolling agent removes endpoint
- uninstalling agent removes endpoint
- changing to a non-defend policy removes endpoint
- removing defend from the policy removes endpoint

Is the integration test that @cmacknz added to this PR relevant here?  https://github.com/elastic/elastic-agent/pull/3086 .  Could help us get coverage in place for the eventual re-introduction of this logs

**Comment by ycombinator** [comment]
> Is the integration test that @cmacknz added to this PR relevant here?  https://github.com/elastic/elastic-agent/pull/3086 .  Could help us get coverage in place for the eventual re-introduction of this logs

Yes, good idea. Instead of closing #3086 unmerged, we'll just trim it down to the integration test.

**Comment by ycombinator** [comment]
@kevinlog I tested the scenarios you mentioned in https://github.com/elastic/elastic-agent/pull/3092#issuecomment-1638765521 on my Mac with an Agent built from this PR.  I also added detailed steps for each scenario to this PR's description.  Each scenario worked _mostly_ as expected; at the start of each scenario, I had to keep manually deleting `/Applications/ElasticEndpoint.app`.  Otherwise, installing Endpoint as part of the subsequent scenario would fail.  Is this a bug?

**Comment by ycombinator** [comment]
buildkite test this

**Review by jlind23 — APPROVED** [review]

**Comment by kevinlog** [comment]
@ycombinator thank you for testing the scenarios!

>  Each scenario worked _mostly_ as expected; at the start of each scenario, I had to keep manually deleting `/Applications/ElasticEndpoint.app`.  Otherwise, installing Endpoint as part of the subsequent scenario would fail.  Is this a bug?

This doesn't sound right, but my question would be if it's a regression or not.  Did the 8.8 Agent/Endpoint behave this way?

@ferullo @nfritts do you know?

**Pull request merged**
