### PR TITLE
Doc Custom Ingest pipeline for k8s integration to enrich deployment and cronjob names

### PR DESCRIPTION
**Pull request by gizas**
- Docs

## What does this PR do?

WHAT: Adds doc example for ingest pipeline needed for metadata enrichment for deployments and cronjobs
WHY: Needed as an alternative to allow users enrich their kubernetes pods now that we have backported https://github.com/elastic/elastic-agent/pull/3591

## Why is it important?

It is needed because users will probably miss wanted deployment and cronjob fields in their deployments

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Relates  #https://github.com/elastic/integrations/issues/8176
- Relates  [#https://github.com/elastic/integrations/issues/8176](https://github.com/elastic/sdh-beats/issues/3863)

## Screenshots

discovery_with_k8s_ingest_pipeline

### CODE REVIEW

**Comment by gizas** [comment]
@elastic/elastic-agent-control-plane could you have a look here please?

**Review by cmacknz — APPROVED** [review]
LGTM, but could this documentation live with the integration itself or as part of the official agent and fleet documentation https://github.com/elastic/ingest-docs/tree/main/docs/en/ingest-management instead?

**Review by pchila — APPROVED** [review]
LGTM, however I agree with @cmacknz  that this should live in the integration or Agent and Fleet documentation (that is where users are most likely to look for it, rather than the agent git repository?

**Comment by gizas** [comment]
Thank you guys I move the relevant PR here https://github.com/elastic/ingest-docs/pull/630. Closing this as duplicate

**Pull request closed without merging**
