### PR TITLE
Failing to detect SSDs in copyDir should not be a fatal error.

### PR DESCRIPTION
**Pull request by cmacknz**
The migration of the agent CI system to buildkite has resulted in a new pipeline with new Mac workers. On those workers there is a new test failure: https://buildkite.com/elastic/elastic-agent/builds/4344#018b6184-da97-4130-8dcf-60f543c6c94a/103-588

```
2023-10-24 11:54:42 UTC | === FAIL: internal/pkg/agent/application/upgrade Test_CopyFile/Existing_but_open,_ignore_errors (0.13s)
-- | --
  | 2023-10-24 11:54:42 UTC | upgrade_test.go:102:
  | 2023-10-24 11:54:42 UTC | Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1698148180680922232/elastic/elastic-agent/internal/pkg/agent/application/upgrade/upgrade_test.go:102
  | 2023-10-24 11:54:42 UTC | Error:      	Not equal:
  | 2023-10-24 11:54:42 UTC | expected: false
  | 2023-10-24 11:54:42 UTC | actual  : true
  | 2023-10-24 11:54:42 UTC | Test:       	Test_CopyFile/Existing_but_open,_ignore_errors
  | 2023-10-24 11:54:42 UTC | Messages:   	ghw.Block() returned error: ioreg unmarshal resulted in 2 I/O device tree nodes
```

The ghw.Block function failing is from https://github.com/jaypipes/ghw which claims directly in its description:

> ghw is a Go library providing hardware inspection and discovery for Linux and Windows. There currently exists partial support for MacOSX.

My guess is that this is a limitation of that library where it is failing to deal with the hardware configuration of the Mac workers here (probably there is some network attached storage through it off).

Regardless of the root cause, this isn't actually a fatal error since we can proceed with the default concurrency level of 1. Especially since this is part of the upgrade process, we should just fall back to a default and attempt the copy and let that fail instead if that is what is going to happen.

### CODE REVIEW

**Comment by cmacknz** [comment]
Not backporting since the original change isn't in 8.11 https://github.com/elastic/elastic-agent/pull/3212

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
```


arsing /build/TEST-go-integration.xml
--
  | 2023-10-25 20:54:04 UTC | /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/parsers/treeparser.rb:96:in `rescue in parse': #<RuntimeError: Illegal character "\\u0000" in raw string "\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u000

...



ime=\\"0.060000\\">" (RuntimeError)
--
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/text.rb:136:in `each'
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/text.rb:136:in `check'
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/text.rb:122:in `initialize'
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/parsers/treeparser.rb:47:in `new'
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/parsers/treeparser.rb:47:in `parse'
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/document.rb:448:in `build'
  | 2023-10-25 20:54:05 UTC | from /usr/local/lib/ruby/gems/3.1.0/gems/rexml-3.2.5/lib/rexml/document.rb:101:in `initialize'
  | 2023-10-25 20:54:05 UTC | from /src/bin/annotate:59:in `new'
  | 2023-10-25 20:54:05 UTC | from /src/bin/annotate:59:in `block in <main>'
  | 2023-10-25 20:54:05 UTC | from /src/bin/annotate:53:in `each'
  | 2023-10-25 20:54:05 UTC | from /src/bin/annotate:53:in `<main>'
  | 2023-10-25 20:54:05 UTC | 💥 Error when processing JUnit tests
````

That's a new one

**Comment by cmacknz** [comment]
buildkite test it

**Review by pchila — APPROVED** [review]
LGTM

**Comment by cmacknz** [comment]
> >>> (linux-amd64-ubuntu-2204) Failed for instance linux-amd64-ubuntu-2204 (@ 34.16.59.95): ogc-linux-amd64-ubuntu-2204-00df unable to continue because stack never became ready: failed to check for cloud 8.12.0-SNAPSHOT to be ready: context deadline exceeded
--

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
This also affects the install command which is now fixed.

**Comment by cmacknz** [comment]
I moved all uses of `ghw.Block` into one place so that this problem is less likely to return.

**Comment by cmacknz** [comment]
I am going to force merge this for the same reason as https://github.com/elastic/elastic-agent/pull/3623#issuecomment-1779603418, the install code is covered by integration tests.

**Pull request merged**
