### PR TITLE
Switch to PAT generated GH token

### PR DESCRIPTION
**Pull request by ev1yehor**
## What does this PR do?
Switch to PAT generated GH token

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- https://github.com/elastic/ingest-dev/issues/3495

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by ev1yehor** [comment]
Was tested in this step. https://buildkite.com/elastic/elastic-agent/builds/10759#0190fe66-20b2-478e-8bc7-553e8991e7f9
Branch was created but issue with reviewer request. Not sure if related to PAT generated token.

**Comment by pazone** [comment]
Shouldn't we add backports?

**Comment by ev1yehor** [comment]
Backport labels was added.

**Review by blakerouse — APPROVED** [review]
Change looks good, seems to work. Failure is unrelated to this change that is a known issue.

**Review by pazone — APPROVED** [review]

**Pull request merged**
