### PR TITLE
feat: upgrade go agent to v2

### PR DESCRIPTION
**Pull request by kruskall**
## What does this PR do?

Update the dependency to v2.

## Why is it important?

go.elastic.co/apm v1 has been deprecated for a while. 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

Can be dropped from the dependency graph completely once https://github.com/elastic/e2e-testing/pull/3845 is merged

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

Closes https://github.com/elastic/elastic-agent/issues/3404

### CODE REVIEW

**Comment by jlind23** [comment]
@pchila I think this will also close https://github.com/elastic/elastic-agent/issues/3404 right?

**Review by pchila — APPROVED** [review]
LGTM

**Review by blakerouse — APPROVED** [review]
Looks good, seems very mechanical change.

**Comment by cmacknz** [comment]
Force merging past the test coverage requirement. This doesn't need unit tests.

**Pull request merged**
