### PR TITLE
ironbank: move to ubi9

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

https://github.com/elastic/elastic-agent/pull/3567 partially changed the `ubi` version to `ubi9` but there were some other changes required in the packaging itself and the base docker images.

## Why is it important?

`ubi9` is not available yet.

## Test

It ran in the CI

image

```bash
$ docker pull docker.elastic.co/observability-ci/elastic-agent-ubi9:52773d50b4496e1e2d5ba82736c69aa7862161e8
$ docker inspect docker.elastic.co/observability-ci/elastic-agent-ubi9:52773d50b4496e1e2d5ba82736c69aa7862161e8 | jq -r '.[0].Config.Labels' | grep ubi
  "com.redhat.component": "ubi9-minimal-container",
```

In addition

```
$ wget https://storage.googleapis.com/fleet-ci-artifacts/elastic-agent/commits/52773d50b4496e1e2d5ba82736c69aa7862161e8/elastic-agent-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz
$ tar xvzf elastic-agent-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz
x ./
x Dockerfile
x LICENSE
x README.md
x config
x config/docker-entrypoint
x hardening_manifest.yaml
$ grep -R ubi
./Dockerfile:ARG BASE_IMAGE=redhat/ubi/ubi9
./hardening_manifest.yaml:  BASE_IMAGE: "redhat/ubi/ubi9"
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by pazone — APPROVED** [review]

**Comment by pierrehilbert** [comment]
It's green now ;-)

**Review by pierrehilbert — APPROVED** [review]
Thx!

**Pull request merged**
