### PR TITLE
Added k8s components to otel distribution

### PR DESCRIPTION
**Pull request by michalpristas**
**Added Extensions**
- `file_storage`

**Added Receivers**
- `kubeletstats` 
- `k8sclusterreceiver` 
- `hostmetricsreceiver` 

**Added Processors**
~~- `resourcedetectionprocessor `~~

~~Fixes: #4723~~
Fixes: #4902 
Fixes: #4724

cc @ChrsMark @AlexanderWert

### CODE REVIEW

**Review by blakerouse — COMMENTED** [review]
Can tests be added to cover that they exists? That way we can ensure a tests catches if they are accidentally removed?

**Comment by AlexanderWert** [comment]
@michalpristas @ycombinator @andrzej-stencel 
Just discussed with @gizas, for the Kubernetes story we will also need:

- `[k8sclusterreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver)`
- [k8sattributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor)

Let's make sure to include those as well (either in this PR or a follow up)

**Comment by ChrsMark** [comment]
`k8sattributesprocessor` is already in: https://github.com/elastic/elastic-agent/pull/4893. So only [k8sclusterreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver) is missing.

**Comment by michalpristas** [comment]
added `k8sclusterreceiver`
let's see if i can fit tests in this sprint

**Review by ChrsMark — APPROVED** [review]
LGTM. I'm fine with adding the tests in follow-up PR(s).

**Comment by ChrsMark** [comment]
@ishleenk17 @AlexanderWert will we need the [`resourcedetection`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.102.0/processor/resourcedetectionprocessor/README.md) processor as well?

**Comment by ishleenk17** [comment]
> @ishleenk17 @AlexanderWert will we need the [`resourcedetection`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.102.0/processor/resourcedetectionprocessor/README.md) processor as well?

Yes, this is needed for getting all the metadata.

**Comment by michalpristas** [comment]
i added `CC0-1.0` license to allow list due to indirect dependency. this should be fine
just FYI @cmacknz

**Review by jlind23 — APPROVED** [review]

**Pull request merged**
