### PR TITLE
Fix TestManager_FakeInput_APM

### PR DESCRIPTION
**Pull request by faec**
Rewrite `TestManager_FakeInput_APM`, which had two main issues:
- The state logic was brittle, and could trigger false failures for uncommon-but-valid state sequences
- Much of the test logic was in a large goroutine without proper shutdown checking, which could cause panics in unrelated tests by reporting an error after the test had already completed

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- [ ] ~~I have added an integration test or an E2E test~~

## Related issues

- Closes https://github.com/elastic/elastic-agent/issues/3715

### CODE REVIEW

**Comment by faec** [comment]
Reverting to draft for a bit to address another issue with the Action handling

**Review by AndersonQ — APPROVED** [review]

**Review by AndersonQ — CHANGES_REQUESTED** [review]
I missed it was put back as draft. I don't think I can just remove the approval, so I'll put this instead.

**Comment by faec** [comment]
Ok, after a long side trail on another PR I've finished reworking this test case

**Review by blakerouse — APPROVED** [review]
Looks good. Thanks for the improvement and the state management additions to the test.

**Comment by cmacknz** [comment]
@AndersonQ please re-review this since your request for changes is blocking it

**Pull request merged**
