### PR TITLE
[Upgrade Watcher] Fix error messages

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR fixes a couple of error messages in the Upgrade Watcher.

## Why is it important?

The error messages were misleading, which makes it confusing when troubleshooting.

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by ycombinator** [comment]
buildkite test this

**Review by pchila — APPROVED** [review]

**Comment by ycombinator** [comment]
@pchila @pierrehilbert Thanks for the review.  I found another location in the Upgrade Watcher that had the wrong log message.  So I've updated this PR with that fix as well.  Please re-review when you get a chance.  Thanks!

**Review by pierrehilbert — APPROVED** [review]

**Comment by pierrehilbert** [comment]
buildkite test this

**Review by pchila — APPROVED** [review]

**Comment by ycombinator** [comment]
buildkite test this

**Comment by ycombinator** [comment]
buildkite test this

**Comment by pierrehilbert** [comment]
Should be okay to be merged once https://github.com/elastic/elastic-agent/pull/3097 is merged

**Comment by pierrehilbert** [comment]
buildkite test this

**Comment by ycombinator** [comment]
This PR has failed on the `TestEnrollAndLog` test a few times (mostly on the same assertion but a couple times on a different assertion 🤷).  I've put up a PR to skip that test as flaky: https://github.com/elastic/elastic-agent/pull/3110.  Once that PR is merged, I'll rebase this PR here on `main`.

**Pull request merged**
