### PR TITLE
Use third-party library for reporting install/uninstall progress

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?
fixes https://github.com/elastic/elastic-agent/issues/3607

This uses a third-party library for creating a spinner that reports progress during install/uninstall operations.

## Why is it important?

The old code was causing some flaky tests, and for such a small bit of code, it was a bit easier to just use a third-party library. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

### CODE REVIEW

**Comment by ycombinator** [comment]
> At that point we're getting kind of complicated for what this is, and we might just want to find a third-party library like https://github.com/schollz/progressbar to just do this for us, which is also an option here. Honestly open to the third-party library idea for a follow-up to this; not sure why we're DIY'ing this.

I'm ++ to using a third-party library here.  I've been thinking along the same lines myself.  The initial implementation was done as one of three OnWeek projects and, at the time, I thought it would be simpler to DIY this especially since we weren't doing anything too fancy like repainting the screen (like some third party progress trackers can do).  I honestly hadn't thought it would introduce so much flakiness and headache.  But after seeing that over the past few weeks, I'm very much in favor of just replacing this with a third-party library at this point.

**Comment by fearful-symmetry** [comment]
Alright, so, it looks like SonarQube is counting all the one-line log statements I added towards the code coverage percentage, which is...not great.

**Comment by ycombinator** [comment]
I like the new progress bar and the time counter too!

There are two things I was wondering if we could change:

1. Would it be possible to display all the steps?  That is, when a step completes, would it be possible to leave it on the screen without it being replaced by the next step?


2. The install ends like so:
   ```
   $ sudo ./elastic-agent install
   Elastic Agent will be installed at /Library/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:y
   Do you want to enroll this Agent into Fleet? [Y/n]:n
   [=   ] Service Started  [11s] Elastic Agent has been successfully installed.
   ```

   The looks a bit odd.  I think we're missing a newline?

**Comment by ycombinator** [comment]
Right after `sudo ./elastic-agent install` is called, there's a spinner but no text is shown next to it.  I managed to capture a screenshot of the moment:

Screenshot 2023-10-19 at 09 14 19

Seems like there should be some text there about the work being done?

I'm not seeing the same behavior during uninstall, though, which is good.

**Comment by ycombinator** [comment]
Thanks @fearful-symmetry, I see the initial message during `sudo elastic-agent install` now.  

One nit:

During uninstallation (`sudo elastic-agent uninstall`), when uninstallation succeeds, the last progress message that's printed is "Done".

```
$ sudo elastic-agent uninstall -f
[ ===] Done  [1s]
Elastic Agent has been uninstalled.
```

However, during installation (`sudo ./elastic-agent install`), when installation succeeds, the last progress message that's printed is the last actual installation step.

```
$ sudo ./elastic-agent install -n
Installing in non-interactive mode.
[==  ] Service Started  [11s]
Elastic Agent has been successfully installed.
```

Could we make these behaviors consistent? I'm not sure which direction makes more sense but I'm leaning slightly towards the way uninstallation behaves.

**Review by ycombinator — APPROVED** [review]
LGTM. Thanks for fixing this, Alex — much needed!

**Review by pchila — APPROVED** [review]
LGTM

**Review by michalpristas — APPROVED** [review]

**Comment by cmacknz** [comment]
I am going to force merge this. Looking at the code that is missing coverage, some of it is covered by integration tests and I don't see value in simulating the 10+ error conditions we can hit just to verify a log line gets printed as expected.

**Comment by orestisfl** [comment]
Just noticed this on a snapshot and it looks amazing :star_struck: :+1:

**Pull request merged**
