### PR TITLE
Add retries to control server connection and ensure logs are captured on failure

### PR DESCRIPTION
**Pull request by cmacknz**
- Closes https://github.com/elastic/elastic-agent/issues/4076

Investigating https://github.com/elastic/elastic-agent/issues/4076 I noticed we were missing logs. My suspicion is that the the test is exiting before the log watchers have a chance to read and write the stdin/stderr streams. Adding a 1 second delay in the affected case appears to have fixed it.

Yes the delay is an arbitrary magic number but I'm unsure of a better way to do this. Ideally we'd just not exit until we read all the logs but I'm not sure of a reasonable way to detect that there are logs pending in the stdout/stderr streams.

Logs are now captured when the test failure of interest happens:

```
=== RUN   TestFakeComponent
    fixture.go:261: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestFakeComponent363186115\001
    fixture.go:274: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestFakeComponent363186115\001
    fixture.go:880: All component specifications where removed
    fixture.go:921: Placed component specifications: fake, fake-shipper
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.207Z","log.origin":{"file.name":"cmd/run.go","file.line":170},"message":"Elastic Agent started","log":{"source":"elastic-agent"},"process.pid":6140,"agent.version":"8.13.0","ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.477Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":126},"message":"Starting upgrade watcher","log":{"source":"elastic-agent"},"path":"C:\\Users\\windows\\AppData\\Local\\Temp\\TestFakeComponent363186115\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\\elastic-agent.exe","args":["C:\\Users\\windows\\AppData\\Local\\Temp\\TestFakeComponent363186115\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\\elastic-agent.exe","watch","--path.config","C:\\Users\\windows\\AppData\\Local\\Temp\\TestFakeComponent363186115\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64","--path.home","C:\\Users\\windows\\AppData\\Local\\Temp\\TestFakeComponent363186115\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64"],"env":[],"dir":"","ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.484Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":133},"message":"Upgrade Watcher invoked","log":{"source":"elastic-agent"},"agent.upgrade.watcher.process.pid":5468,"agent.process.pid":6140,"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.484Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":121},"message":"releasing watcher 5468","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.484Z","log.origin":{"file.name":"cmd/run.go","file.line":259},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.506Z","log.origin":{"file.name":"application/application.go","file.line":62},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.535Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["fake-apm","fake"],"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.535Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":48},"message":"Capabilities file not found in C:\\Users\\windows\\AppData\\Local\\Temp\\TestFakeComponent363186115\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\\capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.535Z","log.origin":{"file.name":"application/application.go","file.line":74},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.845Z","log.origin":{"file.name":"application/application.go","file.line":131},"message":"Elastic Agent has been started in testing mode and is managed through the control protocol","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.862Z","log.logger":"control","log.origin":{"file.name":"server/server.go","file.line":88},"message":"GRPC control socket listening at npipe:///hJ9D1yd8LDiUSmJucqaE1EFaSmA1yPv_.sock","log":{"source":"elastic-agent"},"address":"npipe:///hJ9D1yd8LDiUSmJucqaE1EFaSmA1yPv_.sock","ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.868Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: protocol not available","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-16T20:53:03.879Z","log.origin":{"file.name":"runtime/manager.go","file.line":209},"message":"Starting grpc control protocol listener on port 6789 with max_message_size 104857600","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    fake_test.go:107: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/fake_test.go:107
        	Error:      	Received unexpected error:
        	            	elastic-agent client received unexpected error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\hJ9D1yd8LDiUSmJucqaE1EFaSmA1yPv_.sock: The system cannot find the file specified."
        	Test:       	TestFakeComponent
--- FAIL: TestFakeComponent (27.57s)
```

It looks to me like the control server has gotten slower to initialize, and we need to add some retries to our connection attempt to give it time to start.

Edit: Got a green build with the retry logic added, hopefully that is the fix.

### CODE REVIEW

**Comment by cmacknz** [comment]
Got a clean build, hoping this is the fix: https://buildkite.com/elastic/elastic-agent/builds/6310

Going to roll the buildkite dice a few times to be sure.

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
> Last error: remove C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9ff4a5\\elastic-agent.exe: Access is denied.

That one was https://github.com/elastic/elastic-agent/issues/3342

🎲

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
Not fixed yet it seems https://buildkite.com/elastic/elastic-agent/builds/6317#018d1856-279a-4d73-9cf2-bf99ee979824

```
=== RUN   TestDiagnosticsCommand
    fixture.go:262: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestDiagnosticsCommand1243640485\001
    fixture.go:275: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestDiagnosticsCommand1243640485\001
    fixture.go:881: All component specifications where removed
    fixture.go:922: Placed component specifications: fake, fake-shipper
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.618Z","log.origin":{"file.name":"cmd/run.go","file.line":170},"message":"Elastic Agent started","log":{"source":"elastic-agent"},"process.pid":1036,"agent.version":"8.13.0","ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.895Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":126},"message":"Starting upgrade watcher","log":{"source":"elastic-agent"},"path":"C:\\Users\\windows\\AppData\\Local\\Temp\\TestDiagnosticsCommand1243640485\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\\elastic-agent.exe","args":["C:\\Users\\windows\\AppData\\Local\\Temp\\TestDiagnosticsCommand1243640485\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\\elastic-agent.exe","watch","--path.config","C:\\Users\\windows\\AppData\\Local\\Temp\\TestDiagnosticsCommand1243640485\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64","--path.home","C:\\Users\\windows\\AppData\\Local\\Temp\\TestDiagnosticsCommand1243640485\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64"],"env":[],"dir":"","ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.902Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":133},"message":"Upgrade Watcher invoked","log":{"source":"elastic-agent"},"agent.upgrade.watcher.process.pid":2716,"agent.process.pid":1036,"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.902Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":121},"message":"releasing watcher 2716","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.902Z","log.origin":{"file.name":"cmd/run.go","file.line":259},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.909Z","log.origin":{"file.name":"application/application.go","file.line":62},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.933Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["fake","fake-apm"],"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.933Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":48},"message":"Capabilities file not found in C:\\Users\\windows\\AppData\\Local\\Temp\\TestDiagnosticsCommand1243640485\\001\\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\\capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:50.933Z","log.origin":{"file.name":"application/application.go","file.line":74},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:51.168Z","log.origin":{"file.name":"application/application.go","file.line":131},"message":"Elastic Agent has been started in testing mode and is managed through the control protocol","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:51.182Z","log.logger":"control","log.origin":{"file.name":"server/server.go","file.line":88},"message":"GRPC control socket listening at npipe:///YcOwZEpz2E1cXUEPbfFP2Y6x2nBBt4rd.sock","log":{"source":"elastic-agent"},"address":"npipe:///YcOwZEpz2E1cXUEPbfFP2Y6x2nBBt4rd.sock","ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:51.201Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: protocol not available","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    log.go:96: {"log.level":"info","@timestamp":"2024-01-17T17:12:51.203Z","log.origin":{"file.name":"runtime/manager.go","file.line":209},"message":"Starting grpc control protocol listener on port 6789 with max_message_size 104857600","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
    diagnostics_test.go:137: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/diagnostics_test.go:137
        	Error:      	Received unexpected error:
        	            	elastic-agent client received unexpected error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: open \\\\.\\pipe\\YcOwZEpz2E1cXUEPbfFP2Y6x2nBBt4rd.sock: The system cannot find the file specified."
        	Test:       	TestDiagnosticsCommand
--- FAIL: TestDiagnosticsCommand (19.97s)
```

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
Taking back out of draft: https://buildkite.com/elastic/elastic-agent/builds/6333

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
I have 6 consecutive buildkite tests without the socket error now. Hoping this is good now but will have to monitor after merge.

**Comment by cmacknz** [comment]
I suspect this is now taking longer after https://github.com/elastic/elastic-agent/pull/3909 which changed how we create the named pipe path, but I did not experimentally confirm this.

**Review by blakerouse — APPROVED** [review]
Fix looks good.

Be surprised that just changing a path caused it to take longer, but being more defensive in the connection is always good.

**Comment by cmacknz** [comment]
It may have been marginally passing before, we don't have enough logging to tell since successful test runs don't log anything.

We are now doing more work to create the socket since we unconditionally use the sha256 fallback path, I wouldn't expect this to take several extra seconds but maybe it was enough to occasionally push us past the limit. This test is flaky and not a permanent failure so that's my guess as to what is happening.

https://github.com/elastic/elastic-agent/blob/71c7cb3e51841f555f305dd373f86fe44cd5576a/pkg/utils/socket_windows.go#L30-L40

**Pull request merged**
