### PR TITLE
[CI] Separated extended testing pipeline

### PR DESCRIPTION
**Pull request by pazone**
## What does this PR do?
Depends on https://github.com/elastic/elastic-agent/pull/4738
Extracting long running integration tests to a separate pipeline. 
Added changeset filters to the main the new pipeline
Added notification context for integration tests

Screenshot 2024-05-15 at 17 36 31

**Important:** Introduces a concurrency group for each type of exteneded tests. The concurrency groups are limited to `8`. That means we can run only 8 jobs of a type simultaneously 

For example: 
```
steps:
  - label: "Serverless integration test"
    key: "serverless-integration-tests"
    concurrency_group: elastic-agent-extended-testing/serverless-integration # <- concurrency group
    concurrency: 8 # <- concurrency limit
    env:
      BEAT_NAME: "elastic-agent"
    command: ...
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Relates https://github.com/elastic/elastic-agent/issues/3674
- Relates https://github.com/elastic/elastic-agent/issues/4710

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by pchila — COMMENTED** [review]
@pazone I don't see anything where we add the required check for PRs to have a green build of the new pipeline... Did I miss it or you still need to add it ?

Looking at the checks for this PR I would say we definitely didn't add the required check in GH :sweat_smile: 

image

and the only listed buildkite build does not contain any integration testing...

If we need to merge the pipeline definition before the GH PR check then we should not remove the existing steps for integration testing until we are fully set up with the new pipeline and check

**Comment by rdner** [comment]
@pchila if I understood correctly this PR only extracts the steps into a separate pipeline and another PR https://github.com/elastic/elastic-agent/pull/4738 is supposed to actually create resources to run it.

Once both of them are merged, we should be able to add a required check in the repository settings.

**Review by pchila — CHANGES_REQUESTED** [review]
We need to hold off merging this until we have the check for the extended testing pipeline on GH PRs

**Review by pchila — COMMENTED** [review]
I remove the request changes review, but I am still worried that some bug may be merged while there are no integration tests running since this PR is removing those steps and there will be no replacement until the new pipeline is created and the check added in the GH repo settings as pointed out by @rdner

**Review by pchila — APPROVED** [review]

**Comment by cmacknz** [comment]
Why are this and https://github.com/elastic/elastic-agent/pull/4738 not a single PR?

**Comment by pazone** [comment]
> Why are this and #4738 not a single PR?

First PR creates the new pipeline on `main`. Then this PR configures it.

**Comment by pazone** [comment]
Found a problem with [packaging](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/2#018f7cdf-81c3-474e-94ec-46266e85c173/529-531) after extracting the pipeline. Solving it

**Review by cmacknz — APPROVED** [review]

**Pull request merged**
