### PR TITLE
Remove the OVERRIDE_AGENT_PACKAGE_VERSION value as 8.13 is now built

### PR DESCRIPTION
**Pull request by pierrehilbert**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by pchila — APPROVED** [review]

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
Failing with:

```

libcloud.common.google.GoogleBaseError: "The zone 'projects/elastic-platform-ingest/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'."
--
  | 2024-01-03 12:05:05 EST | 2024-01-03T17:04:46Z <Greenlet at 0x7f69ae4c96c0: _up_async(<LayoutModel: 14>)> failed with GoogleBaseError

```

**Comment by cmacknz** [comment]
The tests failures here are definitely suspicious:

```
upgrader.go:231: Upgrading from version "7.17.16" to version "8.13.0-SNAPSHOT"
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent upgrade 8.13.0-SNAPSHOT --source-uri file:///home/ubuntu/agent/.agent-testing/local --skip-verify]
    upgrader.go:275: waiting for upgrade watcher to start
    upgrader.go:280: upgrade watcher started
    upgrader.go:285: Checking upgrade details state while Upgrade Watcher is running
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent version --binary-only --yaml]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    upgrade_standalone_test.go:51: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_standalone_test.go:51
        	Error:      	Received unexpected error:
        	            	failed waiting for status: context deadline exceeded
        	            	could not unmarshal agent status output: error: context deadline exceeded, output: 
        	            	unexpected end of JSON input
        	Test:       	TestStandaloneUpgrade/Upgrade_7.17.16_to_8.13.0-SNAPSHOT
    fixture_install.go:127: [test TestStandaloneUpgrade/Upgrade_7.17.16_to_8.13.0-SNAPSHOT] Inside fixture cleanup function
    fixture_install.go:142: collecting diagnostics; test failed
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent diagnostics -f /home/ubuntu/agent/build/diagnostics/TestStandaloneUpgrade-Upgrade_7.17.16_to_8.13.0-SNAPSHOT-diagnostics-2024-01-05T09:35:37Z.zip]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent uninstall --force]
```

**Comment by cmacknz** [comment]
The test failure here reproduces when I run this test locally, so there is something legitimately wrong here. 

@ycombinator anything come to mind, this feels like something we already fixed. I'm also not sure why renaming the agent from 8.12.0-SNAPSHOT to 8.13.0-SNAPSHOT would change anything:

```
    upgrade_standalone_test.go:51: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_standalone_test.go:51
        	Error:      	Received unexpected error:
        	            	failed waiting for status: context deadline exceeded
        	            	could not unmarshal agent status output: error: context deadline exceeded, output: 
        	            	unexpected end of JSON input
        	Test:       	TestStandaloneUpgrade/Upgrade_7.17.16_to_8.13.0-SNAPSHOT
```

Unless `/opt/Elastic/Agent/elastic-agent upgrade 8.13.0-SNAPSHOT --source-uri file:///home/ubuntu/agent/.agent-testing/local --skip-verify` is actually downloading 8.13.0-SNAPSHOT and that is out of date. That shouldn't cause this failure though.

**Comment by ycombinator** [comment]
>  I'm also not sure why renaming the agent from 8.12.0-SNAPSHOT to 8.13.0-SNAPSHOT would change anything (since that is the only real change here from the agent perspective).

I think this can be explained by the fact that the version being upgraded to (`endVersion` in the test code) would be `8.13.0`, which would then correctly cause this flag is being set to `false`: https://github.com/elastic/elastic-agent/blob/602a2b4587a8050b38881ad9e5811be79b4562c1/testing/upgradetest/upgrader.go#L178-L188.

And that, in turn, would cause a couple of assertions further in the test to (rightfully) be in play:

https://github.com/elastic/elastic-agent/blob/602a2b4587a8050b38881ad9e5811be79b4562c1/testing/upgradetest/upgrader.go#L282-L290

https://github.com/elastic/elastic-agent/blob/602a2b4587a8050b38881ad9e5811be79b4562c1/testing/upgradetest/upgrader.go#L323-L331

I can see from the error that the test is failing as part of the first assertion mentioned above.  But I don't understand why, as a local build of `8.13.0` Agent should have the necessary changes for the assertion to pass.

As this failure can be reproduced locally, what is the output of `elastic-agent status` while the test is running, right after the upgrade watcher has started up? Also, for good measure, what are the contents of the `.update-marker` file at the same time?

**Comment by cmacknz** [comment]
There are no upgrade details here because 7.17 is too old to write them. Then again so is the 8.11.4 version used in the minor version - 2 test. The biggest difference between 7.17 and 8.11.4 is 7.17 is using the "old" version of the watcher.

This logic came in as part of https://github.com/elastic/elastic-agent/pull/3827 which isn't in 8.12 yet, so my biggest concern that this represents a hidden problem to fix before 8.12 is released is probably taken care of.

**Comment by cmacknz** [comment]
The 8.12 backport of https://github.com/elastic/elastic-agent/pull/3927 did not update the version gating the logic in the test so this problem has been there but hiding from us in all of our test runs.

**Comment by cmacknz** [comment]
This might just be because of the 7.17 watcher running, it is too old to write the watching state out so the test is expecting upgrade details but they don’t exist. 8.11.4 runs the 8.13 watcher which knows to write the upgrade details file. So this is looking like a test bug and not an agent bug.

I ran the 7.17.x to 8.13.x upgrade myself manually and it works fine.

**Comment by ycombinator** [comment]
> The 8.12 backport of #3927 did not update the version gating the logic in the test so this problem has been there but hiding from us in all of our test runs.

Yup, miss on my part.  At this point, we should just update the minimum version in the guard to `8.12.0` both on `main` and in the `8.12` branch, since the necessary code is in both branches now.  Here's the PR to `main` that I'll backport to `8.12` after it's merged: https://github.com/elastic/elastic-agent/pull/4036

**Comment by ycombinator** [comment]
> This might just be because of the 7.17 watcher running, it is too old to write the watching state out so the test is expecting upgrade details but they don’t exist. 8.11.4 runs the 8.13 watcher which knows to write the upgrade details file. So this is looking like a test bug and not an agent bug.
> 
> I ran the 7.17.x to 8.13.x upgrade myself manually and it works fine.

But looking at the test failure, the error is:

```
could not unmarshal agent status output: error: context deadline exceeded, output: 
unexpected end of JSON input
```

That seems like `elastic-agent status --output json` is failing. So the test isn't even getting to the checks related to upgrade details being in the upgrade marker.  

If the upgrade from `7.17.x` to `8.13.x` works manually, that does seem to suggest a test bug rather than an agent bug.  But it would still be good to know why `elastic-agent status --output json` is failing.  Investigating...

**Comment by ycombinator** [comment]
> I ran the 7.17.x to 8.13.x upgrade myself manually and it works fine.

How were you able to run this? I tried this with standalone Agent (with `--source-uri file:///path/to/build/distributions --skip-verify`) and also via Fleet running `8.13.0-SNAPSHOT` in CFT. In either case I get an `unknown hash` error.

**Comment by cmacknz** [comment]
> How were you able to run this? I tried this with standalone Agent (with --source-uri file:///path/to/build/distributions --skip-verify) and also via Fleet running 8.13.0-SNAPSHOT in CFT. In either case I get an unknown hash error.

I also had this problem, it was because I'm on an M1 Mac but we don't publish ARM packages for 7.17. Once I built the X86 darwin package locally the error went away. Likely the upgrade should have failed with a better error message.

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent/pull/4038 has the fix needed to get this merged.

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
Test failure is unrelated, force merging.

**Comment by cmacknz** [comment]
```

Error: error running test: failed to prepare instance ogc-windows-amd64-2022-default-f008: failed to install chocolatey: could not run "powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command \"[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))\"" though SSH: Process exited with status 1 (stdout: , stderr: Exception calling "DownloadString" with "1" argument(s): "The remote name could not be resolved:
--
  | 2024-01-09 14:14:48 EST | 'community.chocolatey.org'"
  | 2024-01-09 14:14:48 EST | At line:1 char:60
  | 2024-01-09 14:14:48 EST | + ... col = 3072; iex ((New-Object System.Net.WebClient).DownloadString('ht ...
  | 2024-01-09 14:14:48 EST | +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | 2024-01-09 14:14:48 EST | + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  | 2024-01-09 14:14:48 EST | + FullyQualifiedErrorId : WebException
```

We keep hitting DNS errors across a few different dependencies.

**Pull request merged**
