### PR TITLE
Create snyk-scan.yml

### PR DESCRIPTION
**Pull request by jlind23**
Snyk github action will perform the tests and then results will be pushed to the Github security tab: https://github.com/elastic/elastic-agent/security

### CODE REVIEW

**Review by ph — COMMENTED** [review]
@jlind23 This looks to work for me.

```
Testing /github/workspace...

Organization:      beats
Package manager:   gomodules
Target file:       go.mod
Project name:      github.com/elastic/elastic-agent
Open source:       no
Project path:      /github/workspace
Licenses:          enabled

✔ Tested 556 dependencies for known issues, no vulnerable paths found.
```

**Review by ph — APPROVED** [review]

**Comment by ph** [comment]
@jlind23 We really need a better way to keep these things in sync for multiple repositories.

**Comment by jlind23** [comment]
@ph agree. @levinebw what would be the best way to setup snyk on multiple repositories without having to update the config in each one individually?

**Comment by ph** [comment]
@jlind23 I think robots might have existing tooling to do just that.

**Comment by levinebw** [comment]
> Snyk github action will perform the tests and then results will be pushed to the Github security tab: https://github.com/elastic/elastic-agent/security

@jlind23 are you sure we are at a stage to push the Snky scan results to a public tab? 

>@levinebw what would be the best way to setup snyk on multiple repositories without having to update the config in each one individually?

I don't know... @jkakavas @thomheymann @jportner may have some thoughts; and/or you can raise a question to support@snyk.io

**Comment by jlind23** [comment]
@levinebw AFAIK code scanning alert is not publicly available, am i wrong?

**Comment by levinebw** [comment]
> @levinebw AFAIK code scanning alert is not publicly available, am i wrong?

I see some content under the public security tab about the job, https://github.com/elastic/elastic-agent/runs/6258878535?check_suite_focus=true, I suppose you are right, the results are not getting pushed publicly

**Pull request merged**
