### PR TITLE
Introduce agent.monitoring.metrics_period

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## What does this PR do?

This PR introduces `agent.monitoring.metrics_period` field

## Why is it important?

I consider this PR important as it allows each user to control the sampling period of monitoring metrics according to them needs

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
~~- [ ] I have added an integration test or an E2E test~~

## Disruptive User Impact

None

## How to test this PR locally

Spawn an agent with setting the config `agent.monitoring.metrics_period` 

## Related issues

- Closes https://github.com/elastic/ingest-dev/issues/2680

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]
Thanks, confirmed it works by reloading a standalone agent configuration and overriding it in a Fleet managed agent using a request like:

```
PUT kbn:/api/fleet/agent_policies/4d16de58-695b-42f2-a006-c9f2f51d7ccd
{
    "name": "Agent policy 1",
    "namespace": "default",
    "overrides": {
      "agent": {
        "monitoring": {
          "metrics_period": "5s"
        }
      }
    }
}
```

Also confirmed the metrics documents are actually arriving at a 5s interval when I made the change above.

**Review by alexsapran — APPROVED** [review]
Thank you very much for the prompt support

**Comment by pierrehilbert** [comment]
As this is an enhancement and not a bug fix I would say we shouldn't.
On the other hand, this change is small enough to limit the risk and could accelerate its usage for our benchmark. 
Will let @cmacknz decide on Monday what is the best option here.

**Comment by cmacknz** [comment]
Yes normally this wouldn't be backported. What problem does backport to 8.14 solve for us? It is small so if it solves a big enough problem we can backport it anyway.

**Comment by amitkanfer** [comment]
> What problem does backport to 8.14 solve for us?

solves 2 problems IMHO:
- Will unblock a team member with a project we've been wanting to do for a long time now :)
- One of the biggest asks is to have a performance benchmark for Agent, this is asked everywhere - and having this fix in place will allow us to start working on it.

So if not a risk - I'm +1 for backporting it ASAP.

**Comment by cmacknz** [comment]
Backport: https://github.com/elastic/elastic-agent/pull/5003/

**Pull request merged**
