### PR TITLE
ironbank: use ubi:9.3

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Bump the `ubi:9` version to `9.3` as requested

## Why is it important?

Ironbank to use the latest secured version

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by v1v** [comment]
I don't know whether there is a need for a changelog entry, @pierrehilbert , do I need one? Or the skipped is good enough?

**Comment by v1v** [comment]
@elastic/elastic-agent-control-plane , I need your 👀  for this PR

**Comment by pierrehilbert** [comment]
We have an opened PR related to this error: https://github.com/elastic/elastic-agent/issues/3792
Would it be okay for you to wait a bit for this to be merged?

**Review by blakerouse — APPROVED** [review]
Looks good.

Sadly non of these changes are really being tested by the integration testing framework. I don't see the need to wait for those fixes for this to be merged.

**Review by amannocci — APPROVED** [review]

**Review by kuisathaverat — APPROVED** [review]

**Comment by v1v** [comment]
@mergifyio rebase

**Comment by v1v** [comment]
post-build step to process the test results failed:

image


This is now ready to be merged

**Pull request merged**
