### PR TITLE
Update gotest.go

### PR DESCRIPTION
**Pull request by jlind23**
Remove -run option as it break test coverage for sonarcloud

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Author's Checklist

- [ ]

## Related issues

- 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by cmacknz** [comment]
> Remove -run option as it break test coverage for sonarcloud

The `-run` option is used to filter the set of tests to be run, and is probably the single most useful argument to `go test`.

How does this break sonarcloud? Why would removing it fix it?

**Comment by jlind23** [comment]
Sonarcloud scan command looked like this before Tiago's change:
`exec: gotestsum --no-color -f standard-quiet --junitfile build/TEST-go-unit.xml --jsonfile build/TEST-go-unit.out.json -- -covermode=atomic -coverprofile=build/TEST-go-unit.cov ./...` 

Now it looks like:
`exec: gotestsum --no-color -f standard-quiet --junitfile build/TEST-go-unit.xml --jsonfile build/TEST-go-unit.out.json -- -covermode=atomic -coverprofile=build/TEST-go-unit.cov -run Unit ./...` 

`-run Unit` has been added to the command and result in code coverage note being ingested because tests are about to be rerun.

**Comment by jlind23** [comment]
Jenkins test this

**Comment by jlind23** [comment]
superseded by https://github.com/elastic/elastic-agent/pull/3052

**Pull request closed without merging**
