### PR TITLE
Reintroduce TestManager_FakeInput_OutputChange

### LINKED ISSUE #2403: TestManager_FakeInput_OutputChange test is flaky
## Flaky Test

This has only been observed on Windows so far.

* **Test Name:** TestManager_FakeInput_OutputChange
* **Branch:** main
* **Platform** Test / Matrix - PLATFORM = 'windows-2016 && windows-immutable' / Test / TestManager_FakeInput_OutputChange

### Stack Trace

```
Test / Matrix - PLATFORM = 'windows-2016 && windows-immutable' / Test / TestManager_FakeInput_OutputChange – github.com/elastic/elastic-agent/pkg/component/runtime
=== RUN   TestManager_FakeInput_OutputChange
    manager_test.go:2480: component fake-0 state changed: {State:STARTING Message:Starting: spawned pid '2136' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STARTING Message:Starting: spawned pid '2136' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STARTING Message:Starting: spawned pid '2136' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STARTING Message:Starting: spawned pid '2136' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000120a20 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc000120ab0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000120b40 err:<nil> logLevel:0}]}
    manager_test.go:2480: component fake-0 state changed: {State:STOPPED Message:Stopped: pid '2136' exited with code '1' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STOPPED Message:Stopped: pid '2136' exited with code '1' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STOPPED Message:Stopped: pid '2136' exited with code '1' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STOPPED Message:Stopped: pid '2136' exited with code '1' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000120a20 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc000120ab0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000120b40 err:<nil> logLevel:0}]}
    manager_test.go:2484: component fake-1 state changed: {State:STARTING Message:Starting: spawned pid '348' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc000120c60 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc000120cf0 err:<nil> logLevel:0}]}
    manager_test.go:2484: component fake-1 state changed: {State:HEALTHY Message:Healthy: communicating with pid '348' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc000120c60 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc000120cf0 err:<nil> logLevel:0}]}
    manager_test.go:2484: component fake-1 state changed: {State:HEALTHY Message:Healthy: communicating with pid '348' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:HEALTHY Message:Fake Healthy 0-0 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-0 unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:HEALTHY Message:Fake Healthy 0-1 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-1 unitPayload:map[] configStateIdx:1 err:<nil>}] VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc000120c60 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc000120cf0 err:<nil> logLevel:0}]}
    manager_test.go:2533: timed out after 30 seconds
--- FAIL: TestManager_FakeInput_OutputChange (34.29s)
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Reintroduces TestManager_FakeInput_OutputChange with a small refactor
 
## Why is it important?

Because it's a test

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

- spin up the windows VM
```
vagrant up win2016
```

- connect to the VM
```
vagrant rdp win2016 
```

it did not work for me. I connected manually using [Remmina](https://remmina.org/how-to-install-remmina/)
create a RDP connection using the following credentials:
```
Server: localhost:33389
user: vagrant
password: vagrant
```

- run the tests
```
cd C:\vagrant>
go test --count=100 --run TestManager_FakeInput_Configure .\pkg\component\runtime\
```
## Related issues

- Closes #2403

### CODE REVIEW

**Review by blakerouse — COMMENTED** [review]
What was the actual fix here to remove the flakiness?

**Comment by AndersonQ** [comment]
> What was the actual fix here to remove the flakiness?

None, I could not reproduce its flakyness, however [this](https://github.com/elastic/elastic-agent/pull/2623/files#diff-93d81f5d6a3d42d955393ea76001d6fd728ef176192f21dd5fee09131a65fbe4L2734), [this](https://github.com/elastic/elastic-agent/pull/2623/files#diff-93d81f5d6a3d42d955393ea76001d6fd728ef176192f21dd5fee09131a65fbe4L2738) and their usage [here](https://github.com/elastic/elastic-agent/pull/2623/files#diff-93d81f5d6a3d42d955393ea76001d6fd728ef176192f21dd5fee09131a65fbe4R2827-R2830) look suspiciously wrong. 

Besides I've run it a few times with `-count=100` or more, and did not find any problem.

**Comment by cmacknz** [comment]
We may need a machine at least as slow as the Windows 2016 Jenkins CI worker to reproduce this.

If we can't find the root cause, we should at least add more logging to be able to tell where the test is stuck when this happens:

```
Test / Matrix - PLATFORM = 'windows-2016 && windows-immutable' / Test / TestManager_FakeInput_OutputChange – github.com/elastic/elastic-agent/pkg/component/runtime
=== RUN   TestManager_FakeInput_OutputChange
    manager_test.go:2480: component fake-0 state changed: {State:STARTING Message:Starting: spawned pid '2136' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STARTING Message:Starting: spawned pid '2136' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STARTING Message:Starting: spawned pid '2136' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STARTING Message:Starting: spawned pid '2136' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000120a20 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc000120ab0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000120b40 err:<nil> logLevel:0}]}
    manager_test.go:2480: component fake-0 state changed: {State:STOPPED Message:Stopped: pid '2136' exited with code '1' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STOPPED Message:Stopped: pid '2136' exited with code '1' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STOPPED Message:Stopped: pid '2136' exited with code '1' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STOPPED Message:Stopped: pid '2136' exited with code '1' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000120a20 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc000120ab0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000120b40 err:<nil> logLevel:0}]}
    manager_test.go:2484: component fake-1 state changed: {State:STARTING Message:Starting: spawned pid '348' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc000120c60 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc000120cf0 err:<nil> logLevel:0}]}
    manager_test.go:2484: component fake-1 state changed: {State:HEALTHY Message:Healthy: communicating with pid '348' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:STARTING Message:Starting: spawned pid '348' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc000120c60 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc000120cf0 err:<nil> logLevel:0}]}
    manager_test.go:2484: component fake-1 state changed: {State:HEALTHY Message:Healthy: communicating with pid '348' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:HEALTHY Message:Fake Healthy 0-0 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-0 unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:HEALTHY Message:Fake Healthy 0-1 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-1 unitPayload:map[] configStateIdx:1 err:<nil>}] VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc000120c60 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc000120cf0 err:<nil> logLevel:0}]}
    manager_test.go:2533: timed out after 30 seconds
--- FAIL: TestManager_FakeInput_OutputChange (34.29s)
```

**Review by blakerouse — APPROVED** [review]
Looks good!

**Pull request merged**
