### PR TITLE
feat: bump gowin32 for arm64 support

### PR DESCRIPTION
**Pull request by kruskall**
## What does this PR do?

bump gowin32 for arm64 support

See https://github.com/winlabs/gowin32/pull/87

## Why is it important?

gowin32 does not support windows arm causing elastic-agent to fail to compile on windows/arm64

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## How to test this PR locally

`GOOS=windows GOARCH=arm64 go build`

## Related issues

- Relates https://github.com/elastic/elastic-agent/issues/692

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Comment by pierrehilbert** [comment]
@kruskall Thanks for contributing (as always).
Do you think we can have the change upstream and therefore use this fork only as a short term solution?

**Comment by pierrehilbert** [comment]
Maybe we can try in parallel to open a PR to see if people are not actively contributing to it but are still okay to review the work?

**Comment by pierrehilbert** [comment]
This is a great news, I'm glad to see this outcome! 
Thanks for considering my idea and to make it succeed haha

**Review by blakerouse — APPROVED** [review]
Awesome!

**Pull request merged**
