### PR TITLE
[Kubernetes Provider] Fix namespace filter on pod and service watchers

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?

The watchers now take into account the `namespace` specified by the user.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## How to test this PR locally

1. Create setup:
```bash
> kind create cluster
> elastic-package stack up -d -v --version=8.15.0-SNAPSHOT
> docker network connect elastic-package-stack_default kind-control-plane
```

2. Build elastic-agent:
```bash
> EXTERNAL=true DEV=true PLATFORMS=linux/amd64 SNAPSHOT=TRUE PACKAGES=docker mage package
```

3. Build docker image:
```bash
> cd build/package/elastic-agent/elastic-agent-linux-amd64.docker/docker-build
> docker build -t custom-agent-image .
```

4. Load this image in your kind cluster:
```bash
> kind load docker-image custom-agent-image:latest
```

5. Deploy elastic agent managed with that image, associate it to a policy with Kubernetes integration with pod data stream enabled. Filter by namespace.

## Related issues

Relates https://github.com/elastic/beats/issues/38978.

### CODE REVIEW

**Comment by constanca-m** [comment]
\test

**Comment by constanca-m** [comment]
> should this be backported to 8.14.2?

The fix is only applied on beats for 8.15 (PR [here](https://github.com/elastic/beats/pull/39881)) @michalpristas, so I am trying to fix it in the same version everywhere @michalpristas

**Review by blakerouse — APPROVED** [review]
Looks good.

We really need to get integration testing for kubernetes.

**Comment by michalpristas** [comment]
@blakerouse you know if we have some backing issue for adding it?

**Comment by pierrehilbert** [comment]
@michalpristas https://github.com/elastic/elastic-agent/issues/4984 would be a first good progress here!

**Review by gizas — APPROVED** [review]

**Review by MichaelKatsoulis — APPROVED** [review]

**Review by tetianakravchenko — APPROVED** [review]

**Pull request merged**
