### PR TITLE
Add linting rules for `replace` directives in go.mod

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR adds a `golangci-lint` linter rule for monitoring the use of `replace` directives in `go.mod`.

## Why is it important?

Developers will sometimes use temporary `replace` directives in `go.mod` while developing a feature or fixing a bug that requires changes in dependencies as well.   The linter rule introduced in this PR will ensure such temporary `replace` directives do not get checked in by accident, by complaining on the PR like so:

Screenshot 2023-05-09 at 16 35 43

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Nice!

**Review by rdner — CHANGES_REQUESTED** [review]
I disagree with this change, the whole point of the linter is to catch things like this.

Why is it a problem to have the linter issue reported in a PR made for development?

The linter does not block the CI or merging, this is only a notification and a reviewer decides whether to approve a PR with a linter issue or not. We should not hide issues only because they don't look nice on PRs.

**Comment by ycombinator** [comment]
@rdner I'm not following what you're suggesting.  The changes to the linter rules in this PR make things _stricter_.  My intention was to have the linter complain on PRs for the following use case:

1. I make a PR in `elastic-agent-libs` for some functionality I need in `elastic-agent`.
2. Next, I make a PR in `elastic-agent` to use the functionality from `elastic-agent-libs`.  To ensure that this PR works, I add a temporary `replace` directive in my `elastic-agent`'s `go.mod` file, something like:
   ```
   replace github.com/elastic/elastic-agent-libs => github.com/ycombinator/elastic-agent-libs v0.0.0-20230511104653-a3c9ee8d16cb
   ```

With the linter changes in this PR, the replace directive will get flagged in CI.  I think this is a good thing as it serves as reminder not to check in that change.   It's not foolproof, yes, but it's better than nothing IMO.  Can you explain why having such an automated check/reminder on the PR is a bad thing?

**Comment by rdner** [comment]
@ycombinator wait, this check was enabled before. That's why I thought you disabled it. Seems like @cmacknz removed it in https://github.com/elastic/elastic-agent/pull/1478 not sure why, there is no explanation. Of course I'm for having this and not against, sorry, I misunderstood the change.

**Review by rdner — APPROVED** [review]

**Review by cmacknz — APPROVED** [review]
Given I left a comment for every removed linter in https://github.com/elastic/elastic-agent/pull/1478/files except this one, I am quite sure I simply removed `gomoddirectives` unintentionally.

**Comment by cmacknz** [comment]
It is also possible I didn't read the linter configuration closely enough to see that `replace-allow-list:` exists to silence the warnings for replace directives we want to keep. Either way,  LGTM.

**Pull request merged**
