### PR TITLE
Add a diagram for CAs and Certs usage between agent, fleet-server and ES

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Add a diagram showing the certificates and CAs used between the Elastic Agent, Fleet Server and Elasticsearch and their respective cli flag.

## Why is it important?

Given the number of possible CAs and certificates and their respective cli options, it's often confusing which one is used on each connection. This diagram helps to explain that.

## Checklist

- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Disruptive User Impact

None

## How to test this PR locally

N/A

## Related issues

- N/A

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by blakerouse — COMMENTED** [review]
This is a really good addition to the documentation. What tool did you use to generate this PDF? If the diagrams are created by code, it would be great to include that in the PR as well. Make it easier for others to update.

That is really the only negative I have with this PR is that updating the PDF if anything changes will not be as simple as updating some code and regenerating the graphs.

**Comment by ycombinator** [comment]
Thanks for adding this to the docs, @AndersonQ.  As Blake said, this is a really useful addition.

Have you considered using something like https://github.blog/developer-skills/github/include-diagrams-markdown-files-mermaid/ to generate the diagrams with code? That will solve the update issue that Blake mentioned as well.

**Comment by AndersonQ** [comment]
I was a "quick" thing I did for Nima, wasn't really intended to be in our docs, but Creaig pointed out that it's better than nothing. I did it on Miro. I can pass it to mermaid

**Comment by nimarezainia** [comment]
thanks for doing this. I was also using it in the *other* doc we are preparing for CA changes.

**Comment by cmacknz** [comment]
We can probably put this in the user facing documentation in https://github.com/elastic/ingest-docs. CC @kilfoyle 

+1 to committing the source somewhere or having this in a place we can more easily maintain (shared Whimsical space?). That said I'd rather have hard to maintain documentation than no documentation.

**Review by michel-laterman — APPROVED** [review]
I agree with the need to add whatever was used to generate the image.
Thanks for making the diagram!

**Comment by AndersonQ** [comment]
I used [miro](https://miro.com/) to make this diagram, nothing special and anyone on platform ingest should be able to access it

**Comment by nimarezainia** [comment]
> We can probably put this in the user facing documentation in https://github.com/elastic/ingest-docs. CC @kilfoyle
> 
> +1 to committing the source somewhere or having this in a place we can more easily maintain (shared Whimsical space?). That said I'd rather have hard to maintain documentation than no documentation.

yeah will add some version of it in to the docs along with the other CA related sections Anderson helped out with.

**Review by blakerouse — APPROVED** [review]
Awesome! Really appreciate adjusting this to be code based, this is great!

**Comment by jlind23** [comment]
Sonarqube is expected but will never be triggered as there was no code change, force merging this to unblock @AndersonQ.

**Pull request merged**
