### PR TITLE
add kubernetes v1.31 to test matrix

### PR DESCRIPTION
**Pull request by mauri870**
## What does this PR do?

Adds test coverage for kubernetes v1.31.0, released Aug 13 2024.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## Related issues

- Relates https://github.com/elastic/observability-dev/issues/3718

### CODE REVIEW

**Comment by blakerouse** [comment]
You should also add it here: https://github.com/elastic/elastic-agent/blob/main/.buildkite/pipeline.yml#L194

**Comment by mauri870** [comment]
> You should also add it here: https://github.com/elastic/elastic-agent/blob/main/.buildkite/pipeline.yml#L194

Missed that one, thanks Blake!

**Review by blakerouse — APPROVED** [review]
+1

**Review by pkoutsovasilis — APPROVED** [review]

**Comment by mauri870** [comment]
@pierrehilbert CI failures seems unrelated, shall we merge this given that the [k8s integration tests](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/3128#01924309-1ee9-4127-b113-e7d3a25525f4) are green?

**Comment by pierrehilbert** [comment]
As the only test failing is the APM one that we already identified (and Blake opened a PR to skip it during our coming investigation to fix it), I will force merge this one.

**Pull request merged**
